### ISSUE TITLE
Trying to leverage Argocd image updater feature to get the updated version of image from container Registry- Unable to establish the connection between Argocd and Argocd Image Updater

### ISSUE THREAD

**Issue by nivedita-atci** [argoproj-labs/argocd-image-updater#113]
error while communicating with ArgoCD" argocd_server="server IP" grpc_web=true grpc_webroot= insecure=false 

"Error: rpc error: code = Unknown desc = Post \"https://ServerIp/application.ApplicationService/List\": x509: cannot validate certificate for ServerIp because it doesn't contain any IP SANs"

Though I have mentioned insecure=false, why certs are getting checked? 

Any help would be highly appreciated.

**Comment by jannfis** [comment]
You should set `argocd.insecure` to true to skip server certificate verification

**Comment by nivedita-atci** [comment]
> You should set `argocd.insecure` to true to skip server certificate verification

Thanks much for the help, yes certificate error vanished by setting argocd.insecure=true, Thanks Again
