### ISSUE TITLE
Not able to use Docker Hub Registry

### ISSUE THREAD

**Issue by nivedita-atci** [argoproj-labs/argocd-image-updater#114]
I have deployed an application in Argocd which uses image present in Docker hub container registry, when we update the image with new version in Docker Container Registry, Argocd Image updater should poll the Docker hub Container registry and update the application with latest verison of the image. This feature is not working. 

Connection has been established between Argocd and Argocd Image updater, I can see in pod logs of Argocd Image updater, 
Starting image update cycle, considering 1 annotated application(s) for update"
time="2020-11-17T09:16:05Z" level=info msg="Processing results: applications=1 images_considered=0 images_skipped=1 images_updated=0 errors=0"

I can see in logs its considering the application for update, but image is getting skipped, can't see any error logs and image is not getting updated for the application.

Logs:

time="2020-11-18T08:01:35Z" level=info msg="Starting health probe server TCP port=8080"
time="2020-11-18T08:01:35Z" level=info msg="Warming up image cache"
time="2020-11-18T08:01:35Z" level=info msg="Finished cache warm-up, pre-loaded 0 meta data entries from 5 registries"
time="2020-11-18T08:01:35Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2020-11-18T08:01:35Z" level=info msg="Processing results: applications=2 images_considered=0 images_skipped=2 images_updated=0 errors=0"
time="2020-11-18T08:03:35Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2020-11-18T08:03:35Z" level=info msg="Processing results: applications=2 images_considered=0 images_skipped=2 images_updated=0 errors=0"
time="2020-11-18T08:05:35Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2020-11-18T08:05:35Z" level=info msg="Processing results: applications=2 images_considered=0 images_skipped=2 images_updated=0 errors=0"
time="2020-11-18T08:07:35Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2020-11-18T08:07:35Z" level=info msg="Processing results: applications=2 images_considered=0 images_skipped=2 images_updated=0 errors=0"
time="2020-11-18T08:09:35Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2020-11-18T08:09:35Z" level=info msg="Processing results: applications=2 images_considered=0 images_skipped=2 images_updated=0 errors=0"

Registry.config looks like,
  accounts.image-updater: apiKey
  argocd.grpc_web: "true"
  argocd.insecure: "true"
  argocd.server_addr: 100.100.100.100
  registries.conf: |
    registries:
    - name: Docker Hub
      api_url: https://argocdhub.docker.io
      ping: yes
      credentials: secret:argocd-image-updater/secrets
      defaultns: library

Any help/leads would be highly appreciated.

@jannfis , Could you please help with  some leads on this.

Many Thanks!

**Comment by jannfis** [comment]
Images are usually skipped for either of the two reasons:

* There is no newer version of the image in the registry or
* The image is not part of the application

Can you try to raise log level to debug by setting `log.level: debug` in `argocd-image-updater-config`, and restart the pod? This should give us a little more hints.

**Comment by nivedita-atci** [comment]
Hi @jannfis , I have enabled the debug log level.

I can see in logs, time="2020-11-20T11:11:00Z" level=debug msg="Image 'hello-kubernetes' seems not to be live in this application, skipping. 

Application is using the image and I am able to access the application as well. 

Any Leads would be highly appreciated.

**Comment by jannfis** [comment]
Can you please post the annotations for image updater you are using?

**Comment by nivedita-atci** [comment]
Hi @jannfis ,

Please find the annotations,

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello-kubernetes
    argocd-image-updater.argoproj.io/hello-kubernetes.update-strategy: latest-first
	argocd-image-updater.argoproj.io/hello-kubernetes.pull-secret: cpaasgitdockerhub
  name: cpaascanary-updater-git
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-private-canary-GithubPackages
    repoURL: https://github.com/nivedita-atci/argocd-example-apps
    targetRevision: HEAD

**Comment by jannfis** [comment]
OK. `argocd-image-updater.argoproj.io/image-list` should be a list of _fully qualified_ image names.

Looking at the source for your application, it probably should be something like: `argocd-image-updater.argoproj.io/image-list: hello-kubernetes=docker.pkg.github.com/nivedita-atci/argocd-example-apps/hello-kubernetes`

Also, looking at your application source, you might want to let the image updater know which of the Helm parameters to set for updating the image. I think you could have success with `argocd-image-updater.argoproj.io/hello-kubernetes.helm.image-spec: image.repository`, given you using the alias from the annotation above.

For more information, please refer to https://argocd-image-updater.readthedocs.io/en/latest/configuration/images/#assigning-aliases-to-images and https://argocd-image-updater.readthedocs.io/en/latest/configuration/images/#specifying-helm-parameter-names

**Comment by nivedita-atci** [comment]
Thanks much for the leads, I could get the images are being considered to be updated now, getting, 

"Could not get tags from registry: Get \"https://docker.pkg.github.com/v2/nivedita-atci/argocd-example-apps/hello-kubernetes/tags/list\": http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"GitHub Docker Registry needs login\\\"}]}\\n\")" alias=hello-kubernetes application=cpaascanary-updater-git image_name=nivedita-atci/argocd-example-apps/hello-kubernetes image_tag=1.8 registry=docker.pkg.github.com

**Comment by jannfis** [comment]
The Git Hub Docker registry requires authentication. In your configuration, but you have only configured a pull secret for a different registry.

**Comment by nivedita-atci** [comment]
Here is ConfigMap file of Argocd-image-updater,

apiVersion: v1
items:
- apiVersion: v1
  data:
    accounts.image-updater: apiKey
    argocd.grpc_web: "true"
    argocd.insecure: "true"
    argocd.server_addr: 20.54.135.45
    log.level: debug
    registries.conf: |
      registries:
      - name: GitHub Docker Packages
        prefix: docker.pkg.github.com
        api_url: https://docker.pkg.github.com
        ping: no
        credentials: dockerconfigjson-github-com

I am getting below error,
time="2020-11-23T08:37:10Z" level=debug msg="Using no version constraint when looking for a new tag" 
alias=hello-kubernetes application=cpaascanary-updater-app image_name=nivedita-atci/argocd-example-apps/hello-kubernetes image_tag=1.8 registry=docker.pkg.github.com

time="2020-11-23T08:37:10Z" level=error msg="Could not set registry endpoint credentials: invalid credential spec: dockerconfigjson-github-com" .

Same credentials have been used while deploying the application and we are able to deploy the application using the image from GitHub packages. When configured the same creds in registries.conf, I am getting error saying couldnot set registry endpoint credentials.

Any Leads would be highly appeciated.

Many Thanks in Advance.

**Comment by jannfis** [comment]
> time="2020-11-23T08:37:10Z" level=error msg="Could not set registry endpoint credentials: invalid credential spec: dockerconfigjson-github-com" .

You need to specify the pull secret in a fully qualified manner (refer https://argocd-image-updater.readthedocs.io/en/latest/configuration/registries/#specifying-credentials-for-accessing-container-registries).

For K8s secrets, the basic syntax is: `<secret_type>:<namespace>#<secret_name>`, where `<secret_type>` is either `secret` for a normal secret, or `pullsecret` for a secret in a classical pull secret format (with JSON contents).

**Comment by jannfis** [comment]
I'm closing this issue. Feel free to reopen if it hasn't been resolved from your PoV.

**Comment by yeskay16** [comment]
Hello @nivedita-atci ,

I am having the same issue. Could you please let me know if you were able to get past this issue ?
