### ISSUE TITLE
Build & publish Docker images for arm64 architecture

### ISSUE THREAD

**Issue by jannfis** [argoproj-labs/argocd-image-updater#136]
**Is your feature request related to a problem? Please describe.**

Currently, Docker images for `argocd-image-updater` are only built & published for amd64 architecture. People might want to run on arm64 architectures.

**Describe the solution you'd like**

We should build & provide official Docker images for arm64 architecture.

**Comment by LS80** [comment]
Might be of some use: https://github.com/argoproj/argo-cd/pull/3554#issuecomment-784145537
