### ISSUE TITLE
Support managing Application CRD using K8S client

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/argocd-image-updater#140]
**Is your feature request related to a problem? Please describe.**

Currently, the image updater retrieves a list of applications using Argo CD API. That requires the creation of an Argo CD token and connection options (such as grpc-web, insecure etc).

We might simplify the initial configuration if the updater is running in the same namespace as Argo CD. In this case list of applications can be extracted using Kubernetes client.

**Describe the solution you'd like**

Add `--applications-source` flag that takes two parameters: `argocd`, `namespace`. If `namespace` is specified then the updater should read applications from the current namespace.

**Additional context**
I think this might improve adoption significantly since this way we support no configuration installation. The user just needs to run `kubectl apply -n argocd -f ...` (or add one more remote base to kustomization file) and the updater should work with public image registries out of the box.

It is still good to support connecting using argocd API. Docker registry might be not available from Argo CD namespace or updater cannot be installed into the same namespace for security reasons.

**Comment by jannfis** [comment]
I like this idea. 

Ideally, we should also make the target namespace also configurable, with a sane default.

 So if `--applications-source` is set to namespace, we should get the target namespace to use via another flag, e.g. `--argocd-namespace` (similar to `--argocd-server-addr`), which defaults to `argocd`.
