### ISSUE TITLE
Git writeback does not work if branch is not specified explicitly

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/argocd-image-updater#149]
**Describe the bug**

The write-back feature works only if the branch is explicitly specified in application source revision. Otherwise it tries to commit to HEAD which does not work. 

**To Reproduce**

Configure writeback for an Argo CD app with empty `targetRevision`. See error in image updater logs

**Expected behavior**

Image updater should detect default branch of origin and use it

**Comment by jannfis** [comment]
This is not actually a bug, and is documented here: https://argocd-image-updater.readthedocs.io/en/latest/configuration/applications/#using-the-git-write-back-method
