### ISSUE TITLE
Declarative configuration for authentication between ArgoCD and ArgoCD Image Updater

### ISSUE THREAD

**Issue by diranged** [argoproj-labs/argocd-image-updater#155]
We would like to deploy the ArgoCD Image Updater - but in our environments, absolutely everything is declaratively deployed through kubernetes resources (Generally with Helm charts). I cannot see any way to declaratively create an authentication token for the image-updater in our ArgoCD system.

I really think that along the lines of #138, I consider the argocd-image-updater simply an additional component to the ArgoCD system.. so it should be able to be deployed along side ArgoCD and just leverage the various secrets and credentials that the ArgoCD system sets up already.

**Describe the solution you'd like**
Bypass token authentication and be able to install argocd-image-updater along side arogcd without any special work for authentication or authorization.

**Comment by mgoodness** [comment]
Does the implementation of #138 not address your use case? It enables the use of Argo CD's repo creds stored in `argocd-cm`.

**Comment by jannfis** [comment]
This has already been implemented by #138 and also #140 and will be part of the upcoming `v0.9.0` release. 

The release is basically ready, but we need to wait for Argo CD v1.9.0 due to a dependency to a new feature in Argo CD.

**Comment by diranged** [comment]
So - actually I think that this was mostly a documentation issue. The documentation (that I found) does not clearly identify that argocd-image-updater can run in `kubernetes` mode where it interfaces directly with the `Application` objects, rather than the argocd web interface. That is great and exactly what I wanted. I have it working now.
