### ISSUE TITLE
evel=info msg="Starting image update cycle, considering 0 annotated application(s) for update"

### ISSUE THREAD

**Issue by a5a5a9** [argoproj-labs/argocd-image-updater#157]
Has anyone experience this with the image updater ? This was initially working fine, I've recreated it a couple of time but the same issue persists.

time="2021-02-22T23:52:33Z" level=info msg="argocd-image-updater v99.9.9+457b52f starting [loglevel:DEBUG, interval:2m0s, healthport:8080]"
time="2021-02-22T23:52:33Z" level=debug msg="rate limit for https://90152327234848.dkr.ecr.us-east-1.amazonaws.com is 2147483647"
time="2021-02-22T23:52:33Z" level=info msg="Loaded 1 registry configurations from /app/config/registries.conf"
time="2021-02-22T23:52:33Z" level=debug msg="Creating in-cluster Kubernetes client"
time="2021-02-22T23:52:33Z" level=debug msg="Using ArgoCD API credentials from environment ARGOCD_TOKEN"
time="2021-02-22T23:52:33Z" level=info msg="ArgoCD configuration: [apiKind=kubernetes, server=argocd-server.argocd.svc.cluster.local, auth_token=true, insecure=true, grpc_web=true, plaintext=true]"
time="2021-02-22T23:52:33Z" level=info msg="Starting health probe server TCP port=8080"
time="2021-02-22T23:52:33Z" level=info msg="Starting metrics server on TCP port=8081"
time="2021-02-22T23:52:33Z" level=info msg="Warming up image cache"
time="2021-02-22T23:52:33Z" level=info msg="Finished cache warm-up, pre-loaded 0 meta data entries from 6 registries"
time="2021-02-22T23:52:33Z" level=info msg="Starting image update cycle, considering 0 annotated application(s) for update"
time="2021-02-22T23:52:33Z" level=info msg="Processing results: applications=0 images_considered=0 images_skipped=0 images_updated=0 errors=0"
time="2021-02-22T23:54:33Z" level=info msg="Starting image update cycle, considering 0 annotated application(s) for update"
time="2021-02-22T23:54:33Z" level=info msg="Processing results: applications=0 images_considered=0 images_skipped=0 images_updated=0 errors=0"
time="2021-02-22T23:56:33Z" level=info msg="Starting image update cycle, considering 0 annotated application(s) for update"
time="2021-02-22T23:56:33Z" level=info msg="Processing results: applications=0 images_considered=0 images_skipped=0 images_updated=0 errors=0"
time="2021-02-22T23:58:33Z" level=info msg="Starting image update cycle, considering 0 annotated application(s) for update"

**Comment by jannfis** [comment]
Hi @a5a5a9, given the fact that you are using `kubernetes` API as access type according to the logs: Have you installed the Image Updater to the same namespace where Argo CD is running in?

I also see that you have `ARGOCD_TOKEN` set-up, and are using an unreleased version (i.e. `latest`), so maybe there's a discrepancy between your configuration and the version you are running? Do you expect Image Updater to use Kubernetes API or Argo CD API?

**Comment by a5a5a9** [comment]
No, the image updater is installed on a separate namespace in the same cluster but that is how it was working before. 

I was not aware of Kubernetes API vs ARGO CD API , as long as I can make it work again it wouldn't matter to me making changes.

**Comment by jannfis** [comment]
I think when you restarted the pod, a new image was pulled containing recent changes. You can either use the v0.8 image in your deployment manifest (this is the general suggestion, since `latest` may contain - as you now experienced - breaking changes), or you will have to specify the API type to be used as `argocd`, either by

1. passing the `--applications-api argocd` command line parameter to the container's startup command or
2. setting `applications_api: argocd` in the `argocd-image-updater-config` ConfigMap and restarting the deployment

**Comment by a5a5a9** [comment]
now getting this **level=error msg="Error: rpc error: code = Unauthenticated desc = invalid session: token contains an invalid number of segments"** I have recreated the TOKEN with no luck


time="2021-02-23T20:43:08Z" level=info msg="argocd-image-updater v0.8.0+18d3e63 starting [loglevel:DEBUG, interval:2m0s, healthport:8080]"
time="2021-02-23T20:43:08Z" level=debug msg="rate limit for https://XXXX.dkr.ecr.us-east-1.amazonaws.com is 2147483647"
time="2021-02-23T20:43:08Z" level=info msg="Loaded 1 registry configurations from /app/config/registries.conf"
time="2021-02-23T20:43:08Z" level=debug msg="Creating in-cluster Kubernetes client"
time="2021-02-23T20:43:08Z" level=debug msg="Using ArgoCD API credentials from environment ARGOCD_TOKEN"
time="2021-02-23T20:43:08Z" level=info msg="ArgoCD configuration: [server=argocd-server.argocd.svc.cluster.local, auth_token=true, insecure=true, grpc_web=false, plaintext=true]"
time="2021-02-23T20:43:08Z" level=info msg="Starting health probe server TCP port=8080"
time="2021-02-23T20:43:08Z" level=info msg="Starting metrics server on TCP port=8081"
time="2021-02-23T20:43:08Z" level=info msg="Warming up image cache"
time="2021-02-23T20:43:08Z" level=error msg="error while communicating with ArgoCD" argocd_server=argocd-server.argocd.svc.cluster.local grpc_web=false grpc_webroot= insecure=true plaintext=true
time="2021-02-23T20:43:08Z" level=error msg="error while communicating with ArgoCD" argocd_server=argocd-server.argocd.svc.cluster.local grpc_web=false grpc_webroot= insecure=true plaintext=true
time="2021-02-23T20:43:08Z" level=error msg="Error: rpc error: code = Unauthenticated desc = invalid session: token contains an invalid number of segments"

**Comment by a5a5a9** [comment]
it is fixed now .
