### ISSUE TITLE
Both metrics and health are being served in both ports.

### ISSUE THREAD

**Issue by magmax** [argoproj-labs/argocd-image-updater#160]
**Describe the bug**
With default configuration, metrics and heath can be accessed from both ports.

**To Reproduce**
1. Start it with any parameters.
2. check the output shows a message like this:
   ```
   INFO[0000] Starting health probe server TCP port=8080   
   INFO[0000] Starting metrics server on TCP port=8081     
   ```
3. run `curl localhost:8080/metrics`, `curl localhost:8081/metrics`, `curl localhost:8080/healthz` and `curl localhost:8081/healthz` to see that all of them worked.

**Expected behavior**
`curl localhost:8080/metrics` and `curl localhost:8081/healthz` should fail.

**Additional context**

**Version**
0.8.0

**Logs**

**Comment by jannfis** [comment]
Oops. Thank you for reporting this, you are right.
