### ISSUE TITLE
Create events for changes

### ISSUE THREAD

**Issue by magmax** [argoproj-labs/argocd-image-updater#164]
**Is your feature request related to a problem? Please describe.**
We need to notify another systems when a version has changed and which is the new tag being used. 

**Describe the solution you'd like**
I'd like to be able to monitor a kubernetes event containing at least:
- resource type ("deployment")
- resource name ("foo")
- tag used ("1.2.3")
- namespace ("foo")
- optionally, previous tag
- optionally, image name and/or repository.

This way we could add another piece to the pipeline to notify external services.

**Describe alternatives you've considered**
I've considered:
- to use [ArgoCD-notifications](https://github.com/argoproj-labs/argocd-notifications), but it only monitors Applications, so it won't know the tag being used.
- to use [kubernetes-event-exporter](https://github.com/opsgenie/kubernetes-event-exporter), configuring a label with the tag, but after running argocd-image-updater the tag disapears, and events might be duplicated due to replication.

**Additional context**
By creating an event, other systems can take it to perform other different actions: notifications (email, slack, pagerduty, ...), maintain a dashboard, monitoring (grafana with tags showing the tag currently used), traceability (logs), ...

**Comment by jannfis** [comment]
Thank you for this idea, @magmax. I do agree that it would be useful to emit Kubernetes events for certain events that happen within Argo CD Image Updater.

**Comment by magmax** [comment]
I've being browsing the code and it doesn't seem to be difficult. I can try to do it by myself, but I have never written anything in golang. I will need some help, specially with tests.
Can you give me this weekend to try, @jannfis ?

**Comment by jannfis** [comment]
@magmax I'd very much appreciate if you go ahead and try to implement it! There's no time pressure at all, and I'll be happy to guide you through any specifics and questions you might have. No worries about no experience with golang, we will work it out together :)

**Comment by magmax** [comment]
Done here: https://github.com/argoproj-labs/argocd-image-updater/pull/167
not sure how to link PR and issues.

**Comment by matthisholleville** [comment]
Well done! 

Do you know when this feature will be included in a release? We are very much looking forward to using this feature!!

**Comment by magmax** [comment]
@matthisholleville It is planned to be launched in version 0.10.0, but I've been waiting for that version around 5 months.

I'm not sure about the roadmap. Maybe @jannfis knows.

**Comment by magmax** [comment]
@matthisholleville ey! it is out!
https://github.com/argoproj-labs/argocd-image-updater/releases/tag/v0.10.0

**Comment by jannfis** [comment]
Yeah, sorry for the delay. Was a little short on time recently :)
