### ISSUE TITLE
Git writeback should not write to the same repository concurrently

### ISSUE THREAD

**Issue by eplightning** [argoproj-labs/argocd-image-updater#175]
**Describe the bug**
Applications are updated concurrently. This speeds up synchronization quite nicely in most cases.
However there are issues when applications that are being synchronized share the same repository (e.g. in monorepos).
That's because executing multiple `git push` commands against the same repository concurrently will result in conflicts.
This gets very noticable when dealing with 10+ apps sharing the same repo (and updating images at the same time).

**To Reproduce**
1. Create multiple applications that use the same repo, set the correct annotations to trigger ArgoCD Image Updater,
2. Push new images for all of these applications,
3. Updating applications will take quite long because ArgoCD Image Updater will need about X synchronization cycles to synchronize all of the applications (where X is the number of applications that need to be synced)

**Expected behavior**
3. ArgoCD Image Updater's synchronization doesn't get noticeably delayed because of shared repository. 

**Additional context**
There's a workaround of setting `--max-concurrency=1` but I think that's a bit of overkill since concurrency is only an issue for a small part of synchronization process.

I have experimented with simple per-repository mutexes for git operations and it works pretty well - but I don't know if that's the best approach:
https://github.com/eplightning/argocd-image-updater/commit/bb5643e125178172c0bdb2769cb6601e0aa79918

**Version**
v0.9.1

**Logs**
```
time="2021-03-26T09:14:55Z" level=error msg="`git push origin master` failed exit status 1: remote: error: cannot lock ref 'refs/heads/master': is at 90345b92413fea6d2df8536dda221723450c37b3 but expected ecfa59f45dc19111db2c0aee69fcfe24509d95cb        \nTo xyz.git\n ! [remote rejected] master -> master (failed to update ref)\nerror: failed to push some refs to 'xyz.git'" execID=AIi9i

time="2021-03-26T09:14:55Z" level=error msg="Could not update application spec: could not push master to origin: `git push origin master` failed exit status 1: remote: error: cannot lock ref 'refs/heads/master': is at 90345b92413fea6d2df8536dda221723450c37b3 but expected ecfa59f45dc19111db2c0aee69fcfe24509d95cb        \nTo xyz.git\n ! [remote rejected] master -> master (failed to update ref)\nerror: failed to push some refs to 'xyz'" application=logowanie
```

**Comment by jannfis** [comment]
Good catch, thank you @eplightning. 

I've taken a look at your change and it seems reasonable to me to use a mutex for locking operations to the Git repository. I would appreciate it if you could send a PR for this (after running `go mod tidy`, as it seems).

Going forward when considering the mono repo scenario, it might be useful to defer the final `git push` for each repository that requires to be updated to somewhere [here](https://github.com/argoproj-labs/argocd-image-updater/blob/b879041c2dc28dd723d1f20991b190de83020d74/cmd/main.go#L175), so all commits could be pushed in a single run. But that would require some serious refactoring. Maybe something to keep in mind for v1.0.0
