### ISSUE TITLE
Rename update strategies to remove confusion

### ISSUE THREAD

**Issue by jannfis** [argoproj-labs/argocd-image-updater#179]
**Is your feature request related to a problem? Please describe.**

Currently, there are four update strategies implemented in Argo CD Image Updater:

* semver - Tracks the latest version using semver constraints
* latest - Tracks the most recently built image
* name - Tracks image versions according to lexical sort
* digest - Tracks a given tag according to its last pushed image's digest

The update strategy names can be confusing, especially `name` and `latest`. `name` is not saying something at all, and `latest` is confused way too often with the convention of the `latest` tag on images (which this method is not suitable for).

**Describe the solution you'd like**

Find suitable, less confusing names for at least `latest` and `name` strategies.

One thought was:

* Rename `latest` to either `recent` or `newer` (because it looks for newer tags in the registry)
* Rename `name` to either `lexical` or `alphabetic` (because it does a lexical sort for finding a suitable tag)

This will be a breaking change, but one that I'd consider necessary to provide more consistency and better usage experience.

**Describe alternatives you've considered**
None

If you have any other suggestions, please let us know them in a comment!

**Comment by NickLarsenNZ** [comment]
With regards to `latest` -> `newer`, to me that suggests a promise of the image tag being newer than what is running. What happens in the case of recent tags being deleted? Would a rollback to the newest tag happen? In which case, perhaps `newest` is more appropriate?

As for `name`, I couldn't see much about docker tags and internationalisation (in my quick search). Maybe `lexical` is the best word here, unless it really is alphabetic? _I'm not quite sure I understand the difference between lexical and alphabetic, but internationalisation is where my mind went_.

**Comment by jannfis** [comment]
I like the suggestion of `newest`, I agree that `newer` may cause misunderstanding as you mentioned.

Maybe the name of the strategy should also make clear the fact that it considers the _build date_ of the image, and not when the image was pushed to the registry (the Docker registry v2 API doesn't give us this particular information). So maybe, `newest-build` would be appropriate?

As for tags and internationalisation, I think there is none. From the [Docker documentation](https://docs.docker.com/engine/reference/commandline/tag/), it states:

> A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

Although they don't clearly state 7-bit or 8-bit ASCII, I would assume that they mean 7-bit and don't support any letters of the extended ASCII table. :shrug:
