### ISSUE TITLE
Git commit to non existing branch

### ISSUE THREAD

**Issue by vsychov** [argoproj-labs/argocd-image-updater#198]
Hello, 

**Is your feature request related to a problem? Please describe.**
If argo cd application created for non-existing project branch e.g. `my-super-feature-branch` and it's not exists yet in git, I expect that argocd-image-updater can create it for me if docker image for that branch in registry exists (something found according to `image-list` and `allow-tags`).

**Describe the solution you'd like**
Add new annotations:
- `git-base-branch` - git branch, that will be used to create branch, specified in `git-branch`
- `application-type` - specify application type (e.g. Helm or Kustomize), because if branch not exists yet, argocd will not return this information

What do you think?

**Comment by nick-homex** [comment]
@jannfis This can be closed now as #304 is merged.
