### ISSUE TITLE
Documentation example typo (for "kustomize.image-name" annotation)

### ISSUE THREAD

**Issue by michaljrk** [argoproj-labs/argocd-image-updater#209]
**Describe the bug**
There is an example in documentation showing `kustomize.image-name` annotation usage with a typo in it (`_`) vs (`-`).

**To Reproduce**
Go to https://argocd-image-updater.readthedocs.io/en/latest/configuration/images/#custom-images-with-kustomize

and check example:

```argocd-image-updater.argoproj.io/<image_alias>.kustomize.image_name: <original_image_name>```
 
 `kustomize.image_name:` is not a valid annotation.
 `kustomize.image-name:` should be used instead.
   
The same situation in the following example as well:

```
argocd-image-updater.argoproj.io/image-list: argocd=ghcr.io/argoproj/argocd
argocd-image-updater.argoproj.io/argocd.kustomize.image_name: quay.io/argoproj/argocd
```

**Expected behavior**
Correct example (without a typo).
```argocd-image-updater.argoproj.io/<image_alias>.kustomize.image-name: <original_image_name>```

**Version**
0.9.4

**Comment by janpieper** [comment]
This has been fixed by https://github.com/argoproj-labs/argocd-image-updater/commit/81d551b3a41f765b705df7efec40f734409e116b.

@jannfis I think we can close this issue 😉

**Comment by jannfis** [comment]
Thanks.
