### ISSUE TITLE
Are there plans to support native k8s manifests?

### ISSUE THREAD

**Issue by perezjasonr** [argoproj-labs/argocd-image-updater#222]
**Is your feature request related to a problem? Please describe.**
It says in the documentation that only kustomize and helm are supported, but if its to parallel param overrides, argocd
allows param overrides for native k8s manifests and other items under the "directory" (ksonnet/jsonnet) category:

the example from docs:

`argocd app set guestbook -p image=example/guestbook:abcd123`

**Describe the solution you'd like**

support of anything that argocd allows us to param override so those too can be part of the image updater/git writeback automation

**Describe alternatives you've considered**

commit desired changes to .argocd-source.yaml manually.

argocd cli using set and -p and just accepting not having changes persist in git. or the direct api equivalent.

**Additional context**

I understand why helm/kustomize would be priority, but for the sake of feature parity it would be nice if argocd and its image updater were consistent on what tools are supported.

**Comment by perezjasonr** [comment]
nevermind, even the cli said no to native manifests:

`FATA[0000] Parameters can only be set against Ksonnet or Helm applications`

**Comment by davidmontoyago** [comment]
could this be reopened or could the team provide an alternative approach for jsonnet manifests? this would make the image updater less opinionated and add an entrypoint for teams using jsonnet.

**Comment by rezonick** [comment]
It can be useful for our use-case too.
Can we re-open this issue?
