### ISSUE TITLE
Tries to lookup for image in registry of tag it should replace

### ISSUE THREAD

**Issue by audriusbla** [argoproj-labs/argocd-image-updater#244]
**Describe the bug**
Image updater tries to lookup for image tags of dockerhub, while annotation is clearly a private registry.

**To Reproduce**
I have `image-placeholder:0.0` in my manifests with kustomize and `some.private.registry.com/image-name:tag` in the Application annotations. it keeps trying to get `https://registry-1.docker.io/v2/library/image-name/tags/list` and fails.

**Expected behavior**
Expected to monitor the registry from annotation

**Additional context**
As a workaround i use literal `registry.local/image-placeholder:0.0` in my manifests and suddenly it just works, though seems like a weird one.
Seems related to this issue one: https://github.com/argoproj-labs/argocd-image-updater/issues/223

**Version**
image-updater: v0.10.2
argocd: v2.0.5+4c94d88

**Logs**
```time="2021-08-24T09:41:24Z" level=info msg="Processing results: applications=2 images_considered=2 images_skipped=0 images_updated=0 errors=2"
time="2021-08-24T09:43:24Z" level=info msg="Starting image update cycle, considering 2 annotated application(s) for update"
time="2021-08-24T09:43:25Z" level=error msg="Could not get tags from registry: Get \"https://registry-1.docker.io/v2/library/image-name/tags/list\": http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Class\\\":\\\"\\\",\\\"Name\\\":\\\"library/image-name\\\",\\\"Action\\\":\\\"pull\\\"}]}]}\\n\")" alias=appimage application=test-app2 image_name=image-placeholder image_tag=0.0 registry=```

**Comment by jannfis** [comment]
Can you please share your annotations?
