### ISSUE TITLE
Image updater removes transformers in kustomization.yaml

### ISSUE THREAD

**Issue by vovando-pomelo** [argoproj-labs/argocd-image-updater#250]
**Describe the bug**
Overwriting parts of kustomization.yaml file wich not supposed to be touched. In this case is transformers. This issue is similar to https://github.com/argoproj-labs/argocd-image-updater/issues/247 

**To Reproduce**
Add to kustomization.yaml:
```
transformers:
- transformers/labels.yaml
```
The updater will remove it if the image is updated.

**Expected behavior**
Image updater doesn't remove transformers section in kustomization.yaml

**Additional context**
N/A

**Version**
0.10.1

**Logs**
N/A

**Comment by jannfis** [comment]
This is probably due to the fact that we import & use Kustomize v2.x - probably we should go for similar version that Argo CD uses (which is v4 as of Argo CD v2.1).

**Comment by thuandt** [comment]
It removed my KSOPS secret generator when I tried to write-back into kustomization.yaml file
