### ISSUE TITLE
Support match applications options beside name

### ISSUE THREAD

**Issue by mubarak-j** [argoproj-labs/argocd-image-updater#258]
**Is your feature request related to a problem? Please describe.**
Currently image-updater seems to come with option to filter or match applications by name e.g `--match-application-name staging-*`. It's common to use k8s labels to filter applications which is currently not supported

**Describe the solution you'd like**
It would be great if image-updater can match applications by labels

**Describe alternatives you've considered**
We considered using `ignore-tags` option but it's not suitable in this use case. 

**Additional context**

**Comment by jannfis** [comment]
Oh, this issue must have been slipped through, sorry. 

I agree, this is a great idea to filter applications by labels and would be nice to have.

**Comment by jaideepr97** [comment]
Hey @jannfis could you assign this to me?
Thanks

**Comment by jannfis** [comment]
Thanks @jaideepr97 - let me know any questions you may have during implementation :+1:

**Comment by jannfis** [comment]
Implemented by #368
