### ISSUE TITLE
Default argocd secret not been used when secret comes from secret template 

### ISSUE THREAD

**Issue by bitgandtter** [argoproj-labs/argocd-image-updater#265]
**Describe the bug**
When argocd it's setup using the secret template the image updater it's not recognize it, it expect the old format where the secret it's also store on the repository

**To Reproduce**
- setup argocd with secret template
- use the argocd default secret

**Expected behavior**
Image updater to check for credentials on both places the old and the new

**Version**
Latest argocd and image updater

**Comment by jannfis** [comment]
We haven't released a version with Argo CD v2.1.x libraries pulled in, that's why it is currently not possible to use repository configuration from secrets. An appropriate change is already in `master` and should be released with the next minor version of Image Updater.

**Comment by jannfis** [comment]
This is included in v0.11.0
