### ISSUE TITLE
Custom git commit message is not used

### ISSUE THREAD

**Issue by nickjn92** [argoproj-labs/argocd-image-updater#277]
**Describe the bug**
Followed the documentation here https://argocd-image-updater.readthedocs.io/en/stable/configuration/applications/#changing-the-git-commit-message, one should edit the `git.commit-message-template` in the `argocd-image-updater-config` configmap to get a custom commit message. Even after restarting the pod no change to the commit message can be seen, it still uses the default message.

**To Reproduce**
* Update `argocd-image-updater-config` configmap and add `git.commt-message-template`with some content to the data field of the config map
* Restart pod
* Publish a new image so that image updater sees this and does a writes to git

**Expected behavior**
I expect the git commit message to be templated to whats inside the `git.commit-message-template`, as per the documentation

**Additional context**

**Version**
Deployed through helm chart
version: 0.2.1
appVersion: v0.10.1

**Logs**
Please paste any relevant logs here

**Comment by jannfis** [comment]
This seems to be a bug in the Helm chart. The image updater manifests have a volume mount for the commit message [here](https://github.com/argoproj-labs/argocd-image-updater/blob/e42f982935566e7f1dd3f322c732727e681ff23a/manifests/base/deployment/argocd-image-updater-deployment.yaml#L111), but this seems to be missing in the Helm chart's version of the deployment resource [here](https://github.com/argoproj/argo-helm/blob/c87255c165ec101123d9e7b7b041efb09fe19322/charts/argocd-image-updater/templates/deployment.yaml#L82)

**Comment by nickjn92** [comment]
Submitted a PR to the argo-helm repository, let me know if i should change anything or if you want to take it over
