### ISSUE TITLE
hitting api requests limit in gcr

### ISSUE THREAD

**Issue by yosefy** [argoproj-labs/argocd-image-updater#313]
**Describe the bug**

we have about 600-700 tags in gcr registry for all the images

updater makes about 5000 api requests to gcr registry each time

running with default interval of 2 min we are hitting the limit of api requests

we are using tags like "prod" to deploy to prod "dev" for dev

**Describe the solution you'd like**
+
**Expected behavior**

only make one request per sha, also start from the end and if the needed tag is found , stop searching

may be some other solution?

**Version**
v0.10.3

**Logs**

time="2021-12-07T11:43:59Z" level=error msg="error fetching metadata for dev-collection/data-utils-server:0.46: Get \"https://gcr.io/v2/ZZZ/YYY/blobs/sha256:97a804dd72026a88ca41869d3d998033ce8c1073af2c621616e15d059a4fb98a\": http: non-successful response (status=429 body=\"Quota Exceeded.\")"

**Comment by jannfis** [comment]
There is actually an (unfortunately, not yet documented - see https://github.com/argoproj-labs/argocd-image-updater/issues/318) tunable for setting the number of requests per second made to each registry endpoint by Image Updater. 

Once the tags have been inspected, the results should be stored in the cache. I guess you hit the limit during cache warmup already?
