### ISSUE TITLE
Document `limit` option for container registries

### ISSUE THREAD

**Issue by janpieper-gcx** [argoproj-labs/argocd-image-updater#318]
**Is your feature request related to a problem? Please describe.**

The ArgoCD Image Updater allows to configure a rate-limit per container registry, but the documentation does not mention this option.

**Describe the solution you'd like**

Document the `limit` option for custom container registries and document what is the default for built-in registries.

**Describe alternatives you've considered**

_None_

**Additional context**

Related page in the documentation: [Configuring Container Registries](https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/)

**Comment by jannfis** [comment]
Fixed by #398
