### ISSUE TITLE
Parsing semantic versions from tags with OS suffixes

### ISSUE THREAD

**Issue by LS80** [argoproj-labs/argocd-image-updater#353]
**Is your feature request related to a problem? Please describe.**
Some image tags have an OS variant suffix such as `alpine` or `debian` which breaks the parsing of the semantic version that precedes it.

**Describe the solution you'd like**
A way to ignore a suffix and parse the remaining part as a semantic version.

**Describe alternatives you've considered**
Currently the workaround seems to be to use the `latest` update strategy with a regex instead of the `semver` strategy.

**Additional context**
An example image with OS variants is [redis](https://hub.docker.com/_/redis/?tab=tags&page=1&name=6.2.6), which Argo CD itself uses.

**Comment by jannfis** [comment]
This is actually possible as of today. You have to allow semver's "prerelease" parsing for that (by giving the constraint a `-0` suffix), and limit the tags to match your desired OS using a regexp, e.g.:

```yaml
argocd-image-updater.argoproj.io/image-list: redis=redis:6.2.x-0
argocd-image-updater.argoproj.io/redis.allow-tags: regexp:^.*-alpine$
```

This works just fine:

```
$ ./dist/argocd-image-updater test library/redis --semver-constraint 6.x.x-0 --allow-tags 'regexp:^.*-alpine$'
DEBU[0000] Creating in-cluster Kubernetes client        
INFO[0000] getting image                                 image_name=library/redis registry=
DEBU[0000] Adding platform linux/amd64                  
INFO[0000] Fetching available tags and metadata from registry  image_name=library/redis
INFO[0002] Found 93 tags in registry                     image_name=library/redis
DEBU[0002] could not parse input tag rc-alpine as semver: Invalid Semantic Version 
DEBU[0002] found 36 from 92 tags eligible for consideration  image=library/redis
INFO[0002] latest image according to constraint is library/redis:6.2.6-alpine 
```

**Comment by LS80** [comment]
Thanks. I did notice the "prerelease" section at https://github.com/Masterminds/semver#working-with-prerelease-versions but I didn't expect it to work for arbitrary suffixes 👍

**Comment by jannfis** [comment]
This should probably go as an example to the docs nevertheless. :)
