### ISSUE TITLE
[docs] Inconsistency in the documentation on git write-back credentials

### ISSUE THREAD

**Issue by zoonoo** [argoproj-labs/argocd-image-updater#354]
**Describe the bug**

I came across this documentation in [configuration/applications.md](https://github.com/argoproj-labs/argocd-image-updater/blob/master/docs/configuration/applications.md), and I noticed that the following two sentences seem to contradict each other : 

 * _[Credentials configured in Argo CD will not be re-used, you have to supply a dedicated set of credentials](https://github.com/argoproj-labs/argocd-image-updater/blame/master/docs/configuration/applications.md#L139)_

* _[By default Argo CD Image Updater re-uses the credentials you have configured in Argo CD for accessing the repository.](https://github.com/argoproj-labs/argocd-image-updater/blame/master/docs/configuration/applications.md#L162)_

Can anyone clarify the actual behaviour and perhaps suggest a fix?

Thanks.

**Version**
master

**Comment by jannfis** [comment]
Closed by #356
