### ISSUE TITLE
Support for registry proxy configuration

### ISSUE THREAD

**Issue by ucrk** [argoproj-labs/argocd-image-updater#360]
**Is your feature request related to a problem? Please describe.**
We need to pull images from a registry which is behind a proxy. 
Unfortunately it seems not to be possible to configure a proxy for this use-case yet.

I tried to add the proxy env vars within the deployment manifest of the image-updater but the connection to the registry still fails.

**Describe the solution you'd like**
It would be great, if it's possible to configure a proxy for the registries within argocd-image-updater-config or globaly with some env vars in the deployment manifest of the image-updater.

**Comment by jannfis** [comment]
Support for leveraging HTTP_PROXY and related environment has already been implemented by https://github.com/argoproj-labs/argocd-image-updater/pull/300, but is not yet released (will be part of upcoming v0.12, but there's no ETA yet)

I agree that a per-repository configuration could come in handy

**Comment by krayne** [comment]
perfect. thanks!

**Comment by ucrk** [comment]
thanks!
