### ISSUE TITLE
BuildDate is always the current time

### ISSUE THREAD

**Issue by NickLarsenNZ** [argoproj-labs/argocd-image-updater#366]
**Describe the bug**

The build date is always the current time.

**To Reproduce**

Run `argocd-image-updater version` twice in a row (at least a second apart).

**Expected behavior**

The actual binary build date time.

**Additional context**

This line gets the runtime datetime:

https://github.com/argoproj-labs/argocd-image-updater/blob/71551f9482bca28351efd062332391a3341725f9/pkg/version/version.go#L11

**Version**

```
/ $ argocd-image-updater version
argocd-image-updater: v0.11.3+f62b7d7
  BuildDate: 2022-01-23T10:22:17Z
  GitCommit: f62b7d7841a42030fe4c75de1951c46b0e7fca2e
  GoVersion: go1.16.13
  GoCompiler: gc
  Platform: linux/amd64
/ $ argocd-image-updater version
argocd-image-updater: v0.11.3+f62b7d7
  BuildDate: 2022-01-23T10:27:13Z
  GitCommit: f62b7d7841a42030fe4c75de1951c46b0e7fca2e
  GoVersion: go1.16.13
  GoCompiler: gc
  Platform: linux/amd64
```

**Logs**
Please paste any relevant logs here

**Comment by NickLarsenNZ** [comment]
Here's a possible way of injecting build data: https://blog.alexellis.io/inject-build-time-vars-golang/#overridegobuild

**version.go**

```go
package main

import (
   // ...
)

var BuildDate string

func newVersionCommand() *cobra.Command {
   // ...
}
```

```sh
go build -ldflags "-X main.BuildDate=$(datetime command here)"
```

**Comment by NickLarsenNZ** [comment]
ArgoCD does it in a similar fashion:

- https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/common/version.go#L8-L30
- https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/Makefile#L127-L133

**Comment by NickLarsenNZ** [comment]
Ah ok, so `argocd-image-updater` does the same:

https://github.com/argoproj-labs/argocd-image-updater/blob/master/Makefile#L32-L35

It's just being overwritten by `time.Now().UTC().Format(time.RFC3339)`. Is that because it is no longer static, so the linker is not updating it (or it is, and the runtime is still updating it)?

**Comment by jannfis** [comment]
Good catch. It _should_ have been overriden at build-time.

https://github.com/argoproj-labs/argocd-image-updater/blob/71551f9482bca28351efd062332391a3341725f9/Makefile#L35

and later

https://github.com/argoproj-labs/argocd-image-updater/blob/71551f9482bca28351efd062332391a3341725f9/Makefile#L71

But for some reason, it doesn't :thinking:

**Comment by jannfis** [comment]
> It's just being overwritten by time.Now().UTC().Format(time.RFC3339). Is that because it is no longer static, so the linker is not updating it (or it is, and the runtime is still updating it)?

If `buildDate` in the version package is set to a static string (e.g. `"unknown"`), the override works as expected. Probably we should set it to an empty string, and the return the value of `time.Now().UTC().Format(time.RFC3339)` in `BuildDate()` when `buildDate` is the empty string (so that it will print a date when run by `go run ...`).

**Comment by NickLarsenNZ** [comment]
Sounds good @jannfis. Just wondering, should we follow how `argocd` does theirs, with a static string of unix epoch?

https://github.com/argoproj/argo-cd/blob/b37eee1054e42c873699460dd5e2447c2f9fe5a6/common/version.go#L12

Or is it quite useful to have the current time when using `go run`?
