### ISSUE TITLE
[Question] ETA on 0.12 and support for http proxy env

### ISSUE THREAD

**Issue by BeyerJC** [argoproj-labs/argocd-image-updater#388]
Hello everyone,

is there a new ETA on the release of 0.12 ? I think the inital planning was end of february. We really need #300 to make the image updater working in our on premise k8s again.

Without the usage of the proxy, we cant communicate with  ghcr.io to check our images.

Im not trying to hurry anyone or demand something, just a question so i can better plan our next steps!

Thanks in advance !

**Comment by jannfis** [comment]
Hi, sorry for the late reply. The 0.12 release will be out in a couple of minutes.
