### ISSUE TITLE
argocd image updater not considering with applicationset resouces

### ISSUE THREAD

**Issue by nishit93-hub** [argoproj-labs/argocd-image-updater#404]
Hi there

Argo image updater considering application if I deploy using resource application but If I deploy the application using resource `applicationSet` then it doesn't consider the application.

I read the docs of  Argocd image updater. its mentioned there that Argocd image only inspects resources of kind application resources.
Can't we use `applicationset` resource Argocd image updater?

**Comment by jannfis** [comment]
I think this has been answered in Slack: https://cloud-native.slack.com/archives/C0296T47CHY/p1647360909833159?thread_ts=1647293057.620689&cid=C0296T47CHY

**Comment by code-R** [comment]
@jannfis 
The above link is not accessible, do we need to join some channel to see that ?

**Comment by akhan23wgu** [comment]
@code-R https://communityinviter.com/apps/cloud-native/cncf
