### ISSUE TITLE
Git write-back method and gpg-signed commits

### ISSUE THREAD

**Issue by vgrigoruk** [argoproj-labs/argocd-image-updater#427]
**Is your feature request related to a problem? Please describe.**
We use `git` write-back method, but our repository has branch protection rules, which require all commits to `main` branch to be signed with a gpg key. It looks like there is partial support for passing gpg key id to the `git commit` command [here](https://github.com/argoproj-labs/argocd-image-updater/blob/master/ext/git/writer.go#L16-L17), but I can not find a way to configure both `CommitOptions.SigningKey` and `CommitOptions.SignOff` options.

**Describe the solution you'd like**
Support configuring these setting via `--git-commit-signing-key` and `--git-commit-sign-off`cli args and `GIT_COMMIT_SIGNING_KEY` and `GIT_COMMIT_SIGN_OFF` env vars [here](https://github.com/argoproj-labs/argocd-image-updater/blob/89daab684fcdac4c4d3a0683fe4764a9c1abd0b4/cmd/run.go#L223-L225) 

**Describe alternatives you've considered**
Disable `require signed commits` requirement in `main` branch protection rules.

**Comment by Den4200** [comment]
Any chance that the changes from the commit that referenced this issue will be ported upstream?

**Comment by smhrazacb** [comment]
same issue, is there any solution?
```
 level=error msg="Could not update application spec: `git -c gpg.format=openpgp commit -a -S -F /tmp/image-updater-commit-msg1731325912` failed exit status 128: error: cannot run
```

**Comment by chengfang** [comment]
This issue should already be resolved by https://github.com/argoproj-labs/argocd-image-updater/pull/710 . From the error above, it looks like the gpg executable is not available.

**Comment by zagr0** [comment]
we have the same errors. gpg executable is missing in the image of updater, shouldn't it be part of it?

**Comment by chengfang** [comment]
This issue is fixed by https://github.com/argoproj-labs/argocd-image-updater/pull/767
