### ISSUE TITLE
Git write-back with SSH key fails with RSA key

### ISSUE THREAD

**Issue by ikaruswill** [argoproj-labs/argocd-image-updater#444]
**Describe the bug**
- I'm running a private git repo using gitea.
- Using an RSA deploy key, I'm able to use Argo CD with that same key
- But with the same key in Argo CD Image Updater, I'm getting `permission denied (public key)`.
- Image updates fail write-back to git
- I know the key works because I'm able to run `ssh -t git@hostname -i id_rsa -vvvv` both locally and in Argo CD repo-server

**To Reproduce**
- When trying to SSH the private git repo in the argocd-image-updater container, it shows the following logs
```
debug1: Offering public key: id_rsa RSA SHA256:somelonghash explicit
debug1: send_pubkey_test: no mutual signature algorithm
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
git@privaterepo.redacted: Permission denied (publickey).
```
- On digging further it seems that it will work if I set the following option in the SSH command
```
-o PubkeyAcceptedKeyTypes=+ssh-rsa
```

**Expected behavior**
SSH works and image updates are commited to git

**Additional context**
Here are the logs of successful SSH connection in the argocd-image-updater container after supplying `PubkeyAcceptedKeyTypes`
```
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: id_rsa RSA SHA256:somelonghash explicit
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: id_rsa RSA SHA256:somelonghash explicit
debug3: sign_and_send_pubkey: RSA SHA256:somelonghash
debug3: sign_and_send_pubkey: signing using ssh-rsa SHA256:somelonghash
debug3: send packet: type 50
debug3: receive packet: type 52
Authenticated to privaterepo.example ([111.111.111.111]:22) using "publickey".
```
(Sensitive details redacted)

**Version**
v0.12.0

**Logs**

**Comment by ikaruswill** [comment]
I just confirmed that using the workaround of mounting a custom `/etc/ssh/ssh_config` that sets:
```
Host privaterepo.example
    PubkeyAcceptedKeyTypes + ssh-rsa
```
argocd-image-updater can now clone and write-back to the repository.

**Comment by kahootali** [comment]
Ideally you should create ssh-keys using this now
```
ssh-keygen -t ecdsa -b 521 -C "your_email@example.com"
```

**Comment by ikaruswill** [comment]
I'm closing this issue for now as the issue is not related to `argocd-image-updater`.

For the benefit of people who end up here in future, the recommended solution to go for is to either:
- Switch to a non-RSA SSH key (ECDSA or ED25519)
- Use token credentials via HTTP Repo URL
