### ISSUE TITLE
Missing ca-certs in docker image

### ISSUE THREAD

**Issue by aborilov** [argoproj-labs/argocd-image-updater#496]
**Describe the bug**
ImageUpdater doesn't work with public docker images using the default configuration

**To Reproduce**
Deploy ImageUpdater without any registry configuration, add argoCD application with public docker hub image and annotate this app for imageupdater

**Expected behavior**
ImageUpdate should work with public docker hub images out of the box

**Additional context**
because ca-certificates are not in the docker images, docker hub ssl cert can't be verified 

**Version**
v0.12.0

**Logs**
```
msg="Could not get tags from registry: Get \"https://registry-1.docker.io/v2/\": x509: certificate signed by unknown authority"
```

**Comment by Mac-lucky** [comment]
Same thing happend to me today
