### ISSUE TITLE
Failed to check new image in ghcr private repo.

### ISSUE THREAD

**Issue by emon5122** [argoproj-labs/argocd-image-updater#510]
Showing log below:
```
time="2022-12-27T07:56:46Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2022-12-27T07:56:46Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
time="2022-12-27T07:56:46Z" level=error msg="Could not get tags from registry: Get \"https://ghcr.io/v2/\": x509: certificate signed by unknown authority" alias=app application=app-backend image_name=test-org/test-img image_tag=latest registry=ghcr.io
```

Annotations using:
`argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/regcred`

I assure regcred is accessible and valid. 

What is causing the issue here?

**Comment by jannfis** [comment]
The essence in this message is

```
Get \"https://ghcr.io/v2/\": x509: certificate signed by unknown authority
```

so probably the Image Updater doesn't know the CA that signed the certificate of `ghcr.io`.

What version of Image Updater are you using?

**Comment by emon5122** [comment]
@jannfis I am using the latest version and I got away with 
`data:
  registries.conf: |
    registries:
    - name: Github Pages
      prefix: ghcr.io
      api_url: https://ghcr.io
      insecure: yes
      ping: no
      credentials: pullsecret:argocd/regcred`
  I had to do insecure: yes

**Comment by emon5122** [comment]
I don't know if I should create another issue, Now I'm facing something new and looking for help.

```
time="2022-12-27T14:59:21Z" level=info msg="Successfully updated image 'ghcr.io/<repo-name>/<image>:1.0.1' to 'ghcr.io/<repo-name>/<image1>:1.0.5', but pending spec update (dry run=false)" alias=image application=example-app image_name=<repo-name>/<image> image_tag=1.0.1 registry=ghcr.io
time="2022-12-27T14:59:21Z" level=info msg="Committing 1 parameter update(s) for application example-app" application=example-app

```
