### ISSUE TITLE
Git write-back filename configurable, it defaults to .argocd-source-{application}.yaml when using Helm

### ISSUE THREAD

**Issue by gcaracuel** [argoproj-labs/argocd-image-updater#551]
**Is your feature request related to a problem? Please describe.**
Imagine 2 different instances of ArgoCD for example in different environments which are configured using the same Helm application with the same Application name (using CRDs hence not easy to rename them without a destroy).
Image Updaters running alongside those ArgoCD would use same exactly same filename for write backs not allowing for example the usage of different strategies. 

**Describe the solution you'd like**
Write-back filename that defaults to .argocd-source-{application}.yaml is somehow configurable so you can use any arbitrary values file. .argocd-source-{application}.yaml  is the only filename of course with values.yaml that is always loaded by ArgoCD but we can force the user to write in a file and be responsible of  use the Image Updater created values.yaml file.

**Comment by zmotu** [comment]
Related PR open since 2021 https://github.com/argoproj-labs/argocd-image-updater/pull/289

**Comment by zmotu** [comment]
Related request in Argo project raised in Dec 2022. https://github.com/argoproj/argo-cd/issues/5109

**Comment by gcaracuel** [comment]
> Related request in Argo project raised in Dec 2022. [argoproj/argo-cd#5109](https://github.com/argoproj/argo-cd/issues/5109)

Nice, this feature request is mostly focused on Image Updater to allow writing on a configurable filename than to cover convention part of ArgoCD which will also add extra automation options.

**Comment by RolandRitt** [comment]
+1

**Comment by askhari** [comment]
I added this PR #636 which allows to specify the write back target as a Helm values file. It's tested on our environment, so any feedback about this would be appreciated.

**Comment by gcaracuel** [comment]
Great work!

**Comment by aqeelat** [comment]
@gcaracuel can you please mark the issue as solved?
