### ISSUE TITLE
Argocd Image Updater complains "Image seems not to be live in this application, skipping"

### ISSUE THREAD

**Issue by yeskay16** [argoproj-labs/argocd-image-updater#565]
kubectl logs pods/argocd-image-updater-5dd76865f6-pgg7s -n argocd

time="2023-05-08T20:44:30Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2023-05-08T20:44:30Z" level=debug msg="Processing application nginx-image-updater-app"
time="2023-05-08T20:44:30Z" level=debug msg="Image 'yeskay16/nginx' seems not to be live in this application, skipping" application=nginx-image-updater-app
time="2023-05-08T20:44:30Z" level=info msg="Processing results: applications=1 images_considered=0 images_skipped=1 images_updated=0 errors=0"

But this application "ginx-image-updater-app" has nginx deployed using the image yeskay16.nginx:v0.1.0. Not sure what I am missing and why argocd complains this ?

Have added docker hub registry details to the argocd-image-updater-configmap:
  registries.conf: |
    registries:
    - name: Docker Hub
      ping: yes
      api_url: https://registry-1.docker.io
      prefix: docker.io
      credentials: secret:argocd/dockcreds#.dockerconfigjson
      defaultns: library

Could you please help me here. have been struggling for 2 days to get past this point.

**Comment by Humayun-nisar** [comment]
Im currently trying to setup Argocd with dockerhub, and getting the same error. How did you manage to fix it?
