### ISSUE TITLE
image updater can not rollout the deployment with error "pending spec update"

### ISSUE THREAD

**Issue by aligolestan** [argoproj-labs/argocd-image-updater#605]
**Describe the bug**

I've setup image updater to update deployments based on image digest on a private image repository.
I have a helm chart in which the image repository and tag are not in their default place and I've put it somewhere else in values.yaml file and its working as it should when deployed via argocd application set.
Problem here is that the image updater can not update these changed specs and returns **`"but pending spec update"`** in the log.

**To Reproduce**

Set application's annotations to get image's digest and update the deployment base on that.
Create a helm chart and instead of having:

```
image: 
  repository: registry.***.com/project/app-front
  tag: latest
```

try to mention the repository and tag somewhere else in the values.yaml file.
for example:

```
deployment:
  spec:
    image:
      repository: registry.***.com/project/app-front
      tag: latest
```

**Expected behavior**

On normal circumstances the image updater shall update the image and its deployment base on the annotations provided.

**Version**

ArgoCD server version: 2.7.2
Image Updater version: 0.12.0
Kubernetes version: 1.25.6

**Logs**

time="2023-08-09T11:02:45Z" level=debug msg="found 1 from 1 tags eligible for consideration" image="registry.private.com/project/app-front:latest"
time="2023-08-09T11:02:45Z" level=info msg="Setting new image to registry.private.com/project/app-front@sha256:8e8a57b11521dd4de100908388ad515c80bcc05ca955c6653fe68dae903fda6a" alias=app-front application=app-front image_name=project/app-front image_tag=dummy registry=registry.private.com
time="2023-08-09T11:02:45Z" level=debug msg="target parameters: image-spec= image-name=image.name, image-tag=image.tag" application=app-front image=registry.private.com/project/app-front
time="2023-08-09T11:02:45Z" level=info msg="Successfully updated image 'registry.private.com/project/app-front@dummy' to 'registry.private.com/project/app-front@sha256:8e8a57b11521dd4de100908388ad515c80bcc05ca955c6653fe68dae903fda6a', **but pending spec update** (dry run=false)" alias=app-front application=app-front image_name=project/app-front image_tag=dummy registry=registry.private.com

**Comment by aligolestan** [comment]
@fwyattblake 

you just need to update your helm chart to the default values like this:

image: 
  repository: registry.***.com/project/app
  tag: latest

**Comment by feraudt** [comment]
Hi @aligolestan 

Not sure if you've found a solution yet but in case you haven't, I stumbled upon the same issue and fixed it by simply modifying my chart to look something like this:

```
components:
  app-front:
    image:
      name: registry.***.com/project/app-front
      tag: default-tag-to-override
```

And I added the following annotations to my argo Application object:

```
argocd-image-updater.argoproj.io/image-list: app-front=registry.***.com/project/app-front
argocd-image-updater.argoproj.io/app-front.helm.image-name: components.app-front.image.name
argocd-image-updater.argoproj.io/app-front.helm.image-tag: components.app-front.image.tag
argocd-image-updater.argoproj.io/front.update-strategy: latest
```

This second part is only required because my Helm chart uses several images and has a more complex structure.
In your case though, my guess is renaming the `repository` field of your chart in a `name` field would fix the problem.
This is because those are the parameters that argocd-image-updater is looking for by default, as you can see [here in their docs](https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#specifying-helm-parameter-names).

I hope this helps.

**Comment by bamaas** [comment]
Have you found a solution? Im having the same problem.

**Comment by oubaydos** [comment]
same problem here

**Comment by Daemoen** [comment]
This bug is still prevalent, and I even changed my deployment manifest using the workaround suggested herein (instead of using image.repository like the op, I moved to image.name).  It does not work.

updater version 0.11.0 (helm chart)

**Comment by jeanmorais** [comment]
Same problem here, but just when I use `ApplicationSet`. When I use the same annotations in `Application` it works well.

**Comment by chengfang** [comment]
> This bug is still prevalent, and I even changed my deployment manifest using the workaround suggested herein (instead of using image.repository like the op, I moved to image.name). It does not work.
> 
> updater version 0.11.0 (helm chart)

The solution above (https://github.com/argoproj-labs/argocd-image-updater/issues/605#issuecomment-1843265674) should work, by ensuring helm values file fields and application annotations are consistent.

**Comment by De4dGho5t** [comment]
This issue still persist even with solution proposed by @feraudt :

In my current setup I'm using image updater in version 0.11.0

My argocd application manifest look like this:

`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medusa
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=clientregistry.azurecr.io/client/dev/backend
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.name
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/backend.update-strategy: alphabetical
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[a-fA-F0-9]{8}$  
    argocd-image-updater.argoproj.io/backend.force-update: 'true'          
    argocd-image-updater.argoproj.io/git-repository: https://gitlab.client.pl/clinet/client-infrastructure
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitlab-client-infrastructure
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  sources:
    - repoURL: registry.client.pl/devops
      targetRevision: 1.3.1
      helm:
        valueFiles:
          - $values/env-configs/dev/medusa/values.yaml
      chart: medusa-js
    - repoURL: https://gitlab.client.pl/client/client-infrastructure
      targetRevision: HEAD
      ref: values
    - repoURL: https://gitlab.client.pl/client/client-infrastructure
      path: env-configs/dev/medusa/external-secrets
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-medusa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true`
      
      
and helm values:

`backend:
  enabled: true
  image: 
    name: client.azurecr.io/client/dev/backend
    tag: latest
    pullPolicy: Always
  replicaCount: 1  
 `      
 
 and image updater correctly create .argocd-source.yaml
 `helm:
  parameters:
  - name: backend.image.name
    value: clinet.azurecr.io/client/dev/backend
    forcestring: true
  - name: backend.image.tag
    value: ba36c0e0
    forcestring: true`
    
   but still in logs :
   
   `time="2024-09-20T09:59:36Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2024-09-20T09:59:36Z" level=info msg="Setting new image to client.azurecr.io/client/dev/backend:ba36c0e0" alias=backend application=medusa image_name=client/dev/backend image_tag=latest registry=client.azurecr.io
time="2024-09-20T09:59:36Z" level=info msg="Successfully updated image 'client.azurecr.io/client/dev/backend:latest' to 'client.azurecr.io/client/dev/backend:ba36c0e0', but pending spec update (dry run=false)" alias=backend application=medusa image_name=client/dev/backend image_tag=latest registry=client.azurecr.io
time="2024-09-20T09:59:37Z" level=info msg="Committing 5 parameter update(s) for application medusa" application=medusa
time="2024-09-20T09:59:37Z" level=info msg="Initializing https://gitlab.client.pl/client/client-infrastructure to /tmp/git-medusa869197813"
time="2024-09-20T09:59:37Z" level=info msg="git fetch origin --tags --force --prune" dir=/tmp/git-medusa869197813 execID=99fcf
time="2024-09-20T09:59:37Z" level=info msg=Trace args="[git fetch origin --tags --force --prune]" dir=/tmp/git-medusa869197813 operation_name="exec git" time_ms=551.396325
time="2024-09-20T09:59:37Z" level=info msg="git config user.name argocd-image-updater" dir=/tmp/git-medusa869197813 execID=e2b73
time="2024-09-20T09:59:37Z" level=info msg=Trace args="[git config user.name argocd-image-updater]" dir=/tmp/git-medusa869197813 operation_name="exec git" time_ms=1.138151
time="2024-09-20T09:59:37Z" level=info msg="git config user.email noreply@argoproj.io" dir=/tmp/git-medusa869197813 execID=5641d
time="2024-09-20T09:59:37Z" level=info msg=Trace args="[git config user.email noreply@argoproj.io]" dir=/tmp/git-medusa869197813 operation_name="exec git" time_ms=1.087159
time="2024-09-20T09:59:37Z" level=info msg="git checkout --force main" dir=/tmp/git-medusa869197813 execID=18a89
time="2024-09-20T09:59:37Z" level=info msg=Trace args="[git checkout --force main]" dir=/tmp/git-medusa869197813 operation_name="exec git" time_ms=6.881711
time="2024-09-20T09:59:37Z" level=info msg="git clean -ffdx" dir=/tmp/git-medusa869197813 execID=95171
time="2024-09-20T09:59:37Z" level=info msg=Trace args="[git clean -ffdx]" dir=/tmp/git-medusa869197813 operation_name="exec git" time_ms=1.3932149999999999
time="2024-09-20T09:59:37Z" level=info msg="Successfully updated the live application spec" application=medusa
time="2024-09-20T09:59:37Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0"`

**Comment by prwnd9** [comment]
Same problem here using helm version 0.11.0 of argocd-image-updater in artifacthub:
https://artifacthub.io/packages/helm/argo/argocd-image-updater/0.11.0

Did someone have a workaround?
Also last version in https://artifacthub.io/packages/helm/argo/argocd-image-updater is 0.11.0, no latest helm chart? 0.15.0? stopped supporting already?

**Comment by chengfang** [comment]
argocd-image-updater images are available in https://quay.io/repository/argoprojlabs/argocd-image-updater?tab=tags

We need to make sure it's documented in README and docs.

**Comment by prwnd9** [comment]
@chengfang 

I can confirm this is working now on image v0.15.0 and helm chart 0.11.1:
https://artifacthub.io/packages/helm/argo/argocd-image-updater/0.11.1

To argocd-image-updater authors and contributors, THANK YOU!

**Comment by TitanRob16** [comment]
I'm still very much experiencing this. 

I have the following annotations:

```
argocd-image-updater.argoproj.io/image-list=<app_name>=europe-docker.pkg.dev/<gcp-project-id>/devops/app_name
argocd-image-updater.argoproj.io/<app_name>.helm.image_tag=image.tag 
argocd-image-updater.argoproj.io/<app_name>.update-strategy=semver
```

In the Argo CD Image Updater pod logs, I see:

```
level=debug msg="found 34 from 34 tags eligible for consideration" image="europe-docker.pkg.dev/<gcp-project-id>/devops/<app_name>:1.0.32"
level=info msg="Setting new image to europe-docker.pkg.dev/<gcp-project-id>devops/<app_name>:1.0.33" alias=<app_name> application=<argo_app_name> image_name=<gcp-project-id>/devops/<app_name> image_tag=1.0.32 registry=europe-docker.pkg.dev
level=debug msg="target parameters: image-spec= image-name=image.name, image-tag=image.tag" application=<argo_app_name> image=europe-docker.pkg.dev/<gcp-project-id>/devops/<app_name> namespace=argocd
level=info msg="Successfully updated image 'europe-docker.pkg.dev/<gcp-project-id>/devops/<app_name>:1.0.32' to 'europe-docker.pkg.dev/<gcp-project-id>/devops/<app_name>:1.0.33', but pending spec update (dry run=false)" alias=<app_name> application=<argo_app_name> image_name=<gcp-project-id>/devops/<app_name> image_tag=1.0.32 registry=europe-docker.pkg.dev
```

The annotations seem to be set correctly, going by the documentation.
This was working fine for us before updating to the 0.11.1 Helm Chart version.
Argo CD is running version: v2.12.6+4dab5bd

Any help with this would be appreciated :)

**Comment by bpk37** [comment]
Using spec.ignoreApplicationDifferences fixed it for me. I am using an ApplicationSet with helm so also needed argocd-image-updater.argoproj.io helm pieces. I needed it for a single application so this is how I solved.

In the ApplicationSet:

```
spec:
  goTemplate: true
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.sources[] | select(.chart == "test-service")
```

In line with the template:
```
  templatePatch: |
    {{- if (eq .path.basenameNormalized "test-service") }}
      metadata:
        annotations:
          argocd-image-updater.argoproj.io/image-list: myimage=imagelocation:latest
          argocd-image-updater.argoproj.io/myimage.update-strategy: digest
          argocd-image-updater.argoproj.io/myimage.helm.image-spec: image
    {{- end }}
```
