### ISSUE TITLE
Support Applications in any namespace

### ISSUE THREAD

**Issue by iandelahorne** [argoproj-labs/argocd-image-updater#611]
**Describe the bug**
With the introduction of [Applications in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#applications-in-any-namespace), applications can now be deployed in namespaces outside of the ArgoCD operator's namespace (default `argocd`). 

However, ArgoCD Image Updater does not support this yet, it only monitors the namespace it's deployed in. We are able to work around this by deploying ArgoCD Image Updater in each namespace we want to utilize it in. For example, if we have applications in the namespaces `team1`, `team2`, team3` that want to utilize the image updater, we deploy 3 instances - each with their own deployment, RBAC et c
 
**To Reproduce**
1. Deploy argocd image updater in the `argocd` namespace
2. Deploy an application in the`argocd` namespace with image update annotations
2. Deploy an application in the `default` namespace with image update annotations
4. The application in the `default` namespace is not updated, but the one in `argocd` is.

**Expected behavior**
The expected behavior is that the application in the `default` namespace is also updated. Ideally there should be a deployment mode similar to other ArgoCD components (such as Argo Rollouts) for deploying as a global controller, as well as a namespaced controller (which is the current behavior)

**Version**
0.12.2

**Comment by renchap** [comment]
Duplicate of #601?

**Comment by iandelahorne** [comment]
Looks to be, dunno how i missed it!
