### ISSUE TITLE
Is this]]

### ISSUE THREAD

**Issue by j-zimnowoda** [argoproj-labs/argocd-image-updater#627]
Hi there,

I like this project. It has quite interesting non intrusive approach with updating images tags in GitOps fashion. However, I am a bit worried about release cycle (last release is from 21.01.2023). 

Can you provide more information regarding the current state of the project? Are there sufficient contributors to ensure its long-term viability? Specifically, in which stages of software development do you require the most active participation?

Cheers

**Comment by aeifn** [comment]
The project seems to be stagnating.

**Comment by pasha-codefresh** [comment]
Hey, the release has been created. There are multiple maintainers supporting the project. 
We will try to create releases each 3 - 4 months , same as ArgoCD doing
