### ISSUE TITLE
client-side throttling

### ISSUE THREAD

**Issue by PatHoo** [argoproj-labs/argocd-image-updater#646]
**Version**

argocd-image-updater: v0.12.2+1aa317c
  BuildDate: 2023-01-21T18:33:35Z
  GitCommit: 1aa317c3c57cdbd3e7f1b7accc99337f112a69e6
  GoVersion: go1.19
  GoCompiler: gc
  Platform: linux/amd64

**Logs**

time="2023-11-17T03:32:02Z" level=info msg="Starting image update cycle, considering 46 annotated application(s) for update"
I1117 03:32:04.337737       1 request.go:665] Waited for 1.110147724s due to client-side throttling, not priority and fairness, request: GET:https://172.17.0.1:443/api/v1/namespaces/argocd/secrets/docker-sp-prod
I1117 03:32:14.537975       1 request.go:665] Waited for 1.745097808s due to client-side throttling, not priority and fairness, request: GET:https://172.17.0.1:443/api/v1/namespaces/argocd/secrets/docker-sp-prod
time="2023-11-17T03:32:19Z" level=info msg="Processing results: applications=46 images_considered=92 images_skipped=0 images_updated=0 errors=0"

**Comment by taliastocks** [comment]
Why do you think it should not be throttling?

**Comment by taliastocks** [comment]
What change fixed this issue?
