### ISSUE TITLE
bug: write back to another branch failed by rejected git push

### ISSUE THREAD

**Issue by javierdompablo** [argoproj-labs/argocd-image-updater#673]
**Describe the bug**
I have configured and argocd application called test-app that tracks a branch called argocd (main is protected). I then setup argocd-image-updater to checkout from master and then push to argocd branch, but I get the below error. How can I force push to the write back branch?

I am following the following steps https://argocd-image-updater.readthedocs.io/en/stable/basics/update-methods/#specifying-a-branch-to-commit-to

**To Reproduce**
argocd-image-updater.argoproj.io/git-branch: master:argocd
argocd-image-updater.argoproj.io/write-back-method: git

**Version**
v2.9.5

**Logs**
```
level=error msg="Could not update application spec: could not push argocd to origin: `git push origin argocd` failed exit status 1: Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.\r\nTo github.com:test-repo.git\n ! [rejected]        argocd -> argocd (non-fast-forward)\nerror: failed to push some refs to 'github.com:test-repo.git'\nhint: Updates were rejected because the tip of your current branch is behind\nhint: its remote counterpart. Integrate the remote changes (e.g.\nhint: 'git pull ...') before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details." application=test-app
```

**Comment by mimartin12** [comment]
I seem to be having the same error in `0.14.0`.
Error:
```
time="2024-10-01T22:02:27Z" level=error msg="`git push origin ephemeral-environment-api-env-test` failed exit status 1: To github.com:org/charts.git\n ! [rejected]        test -> test (non-fast-forward)\nerror: failed to push some refs to 'github.com:org/charts.git'\nhint: Updates were rejected because the tip of your current branch is behind\nhint: its remote counterpart. If you want to integrate the remote changes,\nhint: use 'git pull' before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details." execID=8587a
```

**Comment by chengfang** [comment]
this is where commit operation happens: https://github.com/argoproj-labs/argocd-image-updater/blob/5403b3ed2adf04904ed14e8992ab8bed70d26abd/pkg/argocd/git.go#L249

We need to consider using `--force` option when a custom target push branch is configured.
