### ISSUE TITLE
the image updater wants to connect to  52.219.169.162 (s3-r-w.eu-central-1.amazonaws.com)

### ISSUE THREAD

**Issue by toralf-hlag** [argoproj-labs/argocd-image-updater#702]
We found it in our logs and do wonder if it is a somehow ArgoCD specific bucket and whether we have to allow it in our Calico policies or not?

**Comment by jannfis** [comment]
Hi @toralf-hlag. I would not know of any particular out-of-the-box scenario where Image Updater would like to connect to any S3 resource, so this seems fishy to me.

**Comment by toralf-hlag** [comment]
The scenario is, that ArgoCD connects to the AWS ECR, which needs then eventually 1 bucket which has to be accessed.
But we drilled down our real problem to something outside of ARgoCD.

Said that, so sry for the noise here.
