### ISSUE TITLE
ArgoCD does not consider images for arch "linux/arm64/v8"

### ISSUE THREAD

**Issue by arontsang** [argoproj-labs/argocd-image-updater#711]
**Describe the bug**
linux/arm64/v8 != linux/arm64

**To Reproduce**
Create a manifest for a multi-arch image with one of the arch being "linux/arm64/v8"
Run ArgoCD image updater in k8s using the "linux/arm64" (note missing v8) image
Create application using digest update against multi-arch image

**Expected behavior**
ArgoCD pattern matches linux/arm64 with linux/arm64/v8

**Version**
0.13.0

**Comment by arontsang** [comment]
Work around.

Explicitly add annotation:

`argocd-image-updater.argoproj.io/app.platforms: 'linux/arm64/v8'`

**Comment by mehrdadpfg** [comment]
we had the same issue 
the problem is that the log indicates
```ignoring OCI manifest sha256:1b86e767c10ce0c0e0e64e183a0065d114adbd38b13638811229a19a2d23c598. Manifest platform: linux/arm64, requested: linux/arm64"```

and it does not tell that actually they are different
@arontsang solution worked for us as well

**Comment by jtklahti** [comment]
Same thing was in #665

**Comment by chengfang** [comment]
Please review the linked PR https://github.com/argoproj-labs/argocd-image-updater/pull/858 , and check if it fixes the problem, and if the change of behavior is acceptable.
