### ISSUE TITLE
terminal prompts disabled

### ISSUE THREAD

**Issue by Ulrar** [argoproj-labs/argocd-image-updater#728]
**Describe the bug**
The original issue was https://github.com/argoproj-labs/argocd-image-updater/issues/621 but that's been closed. The newest release does not panic anymore, but as indicated in that now closed issue it left it's place to a new problem : 
```
time="2024-05-29T15:47:24Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: error: cannot run argocd: No such file or directory\nfatal: could not read Username for '<my git repo>': terminal prompts disabled" execID=d3b0c
```

Downgrading back to 0.12 fixes the issue.

**Version**
v0.13.1

**Comment by CygnusHyoga** [comment]
I'm having the same problem with original issue #621 in v0.13, after update to v0.13.1, I get the "terminal prompts disabled" error.

**Comment by pasha-codefresh** [comment]
@jannfis reworked this part completely here, but we planned release it as part of v0.14 , If issue still exists, probably we will cherry pick this change earlier . @jannfis thoughts on it ?

**Comment by jannfis** [comment]
@pasha-codefresh It's a big change, and imho should go into 0.14. We could go ahead and release a 0.14 soon, though. I do not see any issue with that :)

**Comment by clambin** [comment]
same here. automatic upgrades are completely broken for me in v0.13.1.

**Comment by srihas619** [comment]
Since https://github.com/argoproj-labs/argocd-image-updater/pull/726 is merged, I thought I could build and test the latest `master` however I ended up with these errors still. I am using GitHub App creds.

Am I missing something alongside changes in that PR? @jannfis  / @pasha-codefresh could you help? 

<details>
  <summary>Image Updater Logs</summary>

    level=trace msg="processing app 'web2' of type 'Helm'" application=web2
    level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
    level=debug msg="Processing application web2"
    level=debug msg="Considering this image for update" alias=argo-play application=web2 image_name=<redacted>/argo-play image_tag=v1 registry=
    level=debug msg="Using no version constraint when looking for a new tag" alias=argo-play application=web2 image_name=<redacted>/argo-play image_tag=v1 registry=
    level=trace msg="No sort option found" image_alias=argo-play image_name=<redacted>/argo-play registry_url=
    level=trace msg="No match annotation found" image_alias=argo-play image_name=<redacted>/argo-play registry_url=
    level=trace msg="No ignore-tags annotation found" image_alias=argo-play image_name=<redacted>/argo-play registry_url=
    level=trace msg="Using runtime platform constraint linux/arm64" image_alias=argo-play image_name=<redacted>/argo-play registry_url=
    level=trace msg="No pull-secret annotation found" image_alias=argo-play image_name=<redacted>/argo-play registry_url=
    level=trace msg="Performing HTTP GET https://registry-1.docker.io/v2/<redacted>/argo-play/tags/list"
    level=trace msg="List of available tags found: [v1 v2]" alias=argo-play application=web2 image_name=<redacted>/argo-play image_tag=v1 registry=
    level=trace msg="Finding out whether to consider v1 for being updateable" image="<redacted>/argo-play:v1"
    level=trace msg="Finding out whether to consider v2 for being updateable" image="<redacted>/argo-play:v1"
    level=debug msg="found 2 from 2 tags eligible for consideration" image="<redacted>/argo-play:v1"
    level=info msg="Setting new image to <redacted>/argo-play:v2" alias=argo-play application=web2 image_name=<redacted>/argo-play image_tag=v1 registry=
    level=debug msg="target parameters: image-spec= image-name=image.repository, image-tag=image.tag" application=web2 image=<redacted>/argo-play
    level=info msg="Successfully updated image '<redacted>/argo-play:v1' to '<redacted>/argo-play:v2', but pending spec update (dry run=false)" alias=argo-play application=web2 image_name=<redacted>/argo-play image_tag=v1 registry=
    level=debug msg="Using commit message: [skip ci] build: automatic update of web2\n"
    level=info msg="Committing 1 parameter update(s) for application web2" application=web2
    level=info msg="Initializing https://github.com/srihas619/argocd-local to /tmp/git-web22660430708"
    level=info msg="git fetch origin --tags --force --prune" dir=/tmp/git-web22660430708 execID=b2f57
    level=error msg="`git fetch origin --tags --force --prune` failed exit status 128: error: cannot run argocd: No such file or directory\nfatal: could not read Username for 'https://github.com': terminal prompts disabled" execID=b2f57
    level=info msg=Trace args="[git fetch origin --tags --force --prune]" dir=/tmp/git-web22660430708 operation_name="exec git" time_ms=238.79500000000002
    level=error msg="Could not update application spec: `git fetch origin --tags --force --prune` failed exit status 128: error: cannot run argocd: No such file or directory\nfatal: could not read Username for 'https://github.com': terminal prompts disabled" application=web2
    level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"

</details>

Thank you!

**Comment by Sovietaced** [comment]
I am experiencing the same issue on `master` using GitHub App creds

**Comment by Sovietaced** [comment]
I'm tracing through the code and I'm bit confused at the error. 

```time="2024-06-03T22:03:07Z" level=error msg="`git fetch origin --tags --force --prune` failed exit status 128: error: cannot run argocd: No such file or directory\nfatal: could not read Username for 'https://github.com': terminal prompts disabled" execID=e7a4a
```

Why does a call to `git fetch` try to run argocd? Is there some sort of git hook being executed? 

https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/argocd/git.go#L159

**Comment by Sovietaced** [comment]
For some reason release 0.13.1 works for me, so looks like #726 is specifically what caused this issue 🤷

**Comment by jannfis** [comment]
Found the issue and have a fix up.

**Comment by jannfis** [comment]
I think this bug hits only if you use an HTTPS based repository configuration. @Sovietaced, are you by chance using SSH connected repositories?

**Comment by Sovietaced** [comment]
> I think this bug hits only if you use an HTTPS based repository configuration. @Sovietaced, are you by chance using SSH connected repositories?

I am using repositories setup with GitHub app credentials with an HTTPS URL.

**Comment by zagr0** [comment]
Is there any workaround for that?
Annotation does not work anymore: `argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds`

**Comment by alexismaior** [comment]
Is this fixed anyway? Running the latest build I'm still getting: 

`level=error msg="Could not update application spec: `git fetch origin --tags --force --prune` failed exit status 128: time=\"2024-06-18T17:51:35Z\" level=fatal msg=\"ARGOCD_GIT_ASKPASS_NONCE is not set\"\nerror: unable to read askpass response from '/usr/local/bin/argocd-image-updater'\nfatal: could not read Username for 'https://github.xxxx': terminal prompts disabled" application=test-app`

Annotations:
```
  annotations: 
   argocd-image-updater.argoproj.io/image-list: app=myrepo/app
   argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[0-9]+.[0-9]+.[0-9]+-[0-9a-f]{7}$  
   argocd-image-updater.argoproj.io/app.helm.image-name: app.image.repository
   argocd-image-updater.argoproj.io/app.helm.image-tag: app.image.tag
   argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-image-updater/git-creds
   argocd-image-updater.argoproj.io/git-repository: https://github.xxxxx
   argocd-image-updater.argoproj.io/write-back-target: "helmvalues:../../values.yaml"
   argocd-image-updater.argoproj.io/git-branch: master:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}} 
```

**Comment by jannfis** [comment]
Thanks for testing and reporting, @alexismaior. Will dig into again.

**Comment by alexismaior** [comment]
Yep. Tested with both HTTPS and SSH git credentials and the image updater was able to write back to git. Thanks, folks, for working on this.

**Comment by alexismaior** [comment]
Are there any plans to release v0.13.2 in the short term with this fix? :D

**Comment by chengfang** [comment]
> Are there any plans to release v0.13.2 in the short term with this fix? :D

See https://github.com/argoproj-labs/argocd-image-updater/pull/748#issuecomment-2208757523

**Comment by younsl** [comment]
After upgrading ArgoCD from 2.9.5 to 2.13.4, I got a 'terminal prompts disabled' error in Argo UI. I was not using [argocd-image-updater](https://github.com/argoproj-labs/argocd-image-updater). All application resources were Out Of Sync and did not work.

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/63e4d43d-1ba9-4c62-ba93-6a904411a8d3" />

- **Reason**: I set the Repository to be used only by a specific project (in my case: default), so only Applications in the default project could sync.
- **How to fix**: In the Repositories settings (VIA HTTPS), do not set the Project field. Leave it empty. This way, all projects can use the GHES token you set in Repositories menu.
- **Recommendation**: It is better to manage Repository settings in ArgoCD Values files using GitOps.

Example of setting repositories in the ArgoCD chart:

```yaml
# helm/argocd/values_my_example.yaml
configs:
  repositories: {}
    # private-helm-repo:
    #   url: https://my-private-chart-repo.internal
    #   name: private-repo
    #   type: helm
    #   password: my-password
    #   username: my-username
```

**Comment by chengfang** [comment]
@younsl thanks for sharing your solutions!
