### ISSUE TITLE
Image Updater not able to connect to Gitlab Repo

### ISSUE THREAD

**Issue by vipul0805** [argoproj-labs/argocd-image-updater#735]
**Describe the bug**
I recently upgraded ArgoCD image updater to the latest version `v0.13.1`. I checked the docs and set the value of `applicationsAPIKind: kubernetes` as both ArgoCd and the image updater run in the same cluster.

After the update the image updater cannot connect to the gitlab repo. Here is the error:

```
level=error msg="`git fetch origin --tags --force` failed exit status 128: error: cannot run argocd: No such file or directory\nfatal: could not read Username for 'http://10.29.218.114:10002': terminal prompts disabled" execID=bbbb3
```

I cannot figure out where it is looking for the credentials.

**Additional context**
In the docs the image updater is reading the token from a secret named `argocd-image-updater-secret`. I do not have any secret created and its not clear from the docs whether it needs to be created if using Method 1 in the Install guide.

**Version**
ArgoCD image updater: v0.13.1
ArgoCD: 2.11.2

**Comment by chengfang** [comment]
The errors are the same in the other issue #728 . Can you check if this is the same issue?
