### ISSUE TITLE
Git 'stable' tag should be updated when official release is cut

### ISSUE THREAD

**Issue by avo-sepp** [argoproj-labs/argocd-image-updater#769]
**Is your feature request related to a problem? Please describe.**
The main ArgoCD project promotes the `stable` tag in Git whenever they cut a tagged release (ignoring pre-releases). This allows us to have a semi-safe auto-upgrade system using ArgoCD+Kustomize. See snippet. ArgoCD updates on stable, but image updater is stuck on a specific version until manually intervened. 

```resources:
  # Argo-CD Resources
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=stable 
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.14.0/manifests/install.yaml # Argo-CD Image Updater
```

I'd really like to update the image updater in the same way. So I don't have to constantly watch this project for updates to our system. 

**Describe the solution you'd like**
Automatically bump the `stable` tag in this repository when a new tagged release is pushed.

**Comment by chengfang** [comment]
Yes, the `stable` tag should be updated as part of the release procedure.

**Comment by chengfang** [comment]
@avo-sepp thanks for reporting the issue. I've updated the `stable` tag to point to the latest stable release (currently `v0.14.0`). See https://github.com/argoproj-labs/argocd-image-updater/tags
