### ISSUE TITLE
Update does not seem to happen

### ISSUE THREAD

**Issue by Zefool** [argoproj-labs/argocd-image-updater#80]
I have a project with a newly published image. I can see the argo-image-updater registering the new arrival, and triggering an update. The update does not however go through. 
Manually changing the app manifest in Argo does translate through to k8s though. So the connections 

Argo-image-updater ->  Repository and 
Argo -> k8s

do work, it seems to be a problem with the connection

Argo-image-updater -> Argo.

**Debug steps**
I tried updating manually (editing the live manifest in the Argo UI), that went swimmingly (all pods deployed correctly).
I tried assigning full admin privileges to the argo-image-updater user in Argo, that did not change anything.
I restarted all pods in various configurations.

**Logs**
```
oc logs argocd-image-updater-<HASH>

time="2020-09-03T11:32:00Z" level=info msg="Processing results: applications=1 images_considered=1 images_updated=1 errors=0"
time="2020-09-03T11:34:00Z" level=debug msg="Starting image update process"
time="2020-09-03T11:34:00Z" level=debug msg="Considering 1 applications with annotations for update"
time="2020-09-03T11:34:00Z" level=debug msg="Processing application $APPLICATION"
time="2020-09-03T11:34:00Z" level=debug msg="Considering this image for update" application=$IMAGE image_name=$REPOSITORY/$IMAGE image_tag=2.1.0-dev.6 registry=$REGISTRY
time="2020-09-03T11:34:00Z" level=debug msg="Using version constraint '>=2.1.0-0' when looking for a new tag" application=$APPLICATION image_name=$REPOSITORY/$IMAGE image_tag=2.1.0-dev.6 registry=$REGISTRY
time="2020-09-03T11:34:00Z" level=debug msg="found 9 from 9 tags eligible for consideration" image="$REGISTRY/$REPOSITORY/$IMAGE:2.1.0-dev.6"
time="2020-09-03T11:34:00Z" level=info msg="Upgrading image to $REGISTRY/$REPOSITORY/$IMAGE:2.1.0-dev.102" application=$APPLICATION image_name=$REPOSITORY/$IMAGE image_tag=2.1.0-dev.6 registry=$REGISTRY
time="2020-09-03T11:34:00Z" level=debug msg="target parameters: image-spec= image-name=, image-tag=" application=$APPLICATION image=$REGISTRY/$REPOSITORY/$IMAGE
time="2020-09-03T11:34:02Z" level=info msg="Successfully updated image '$REGISTRY/$REPOSITORY/$IMAGE:2.1.0-dev.6' to '$REGISTRY/$REPOSITORY/$IMAGE:2.1.0-dev.102'" application=$APPLICATION image_name=$REPOSITORY/$IMAGE image_tag=2.1.0-dev.6 registry=$REGISTRY
time="2020-09-03T11:34:02Z" level=info msg="Processing results: applications=1 images_considered=1 images_updated=1 errors=0"
```

I believe the following of those lines hints at a problem: 
`time="2020-09-03T11:34:00Z" level=debug msg="target parameters: image-spec= image-name=, image-tag=" application=$APPLICATION image=$REGISTRY/$REPOSITORY/$IMAGE`

```
oc logs argocd-server-<HASH>

time="2020-09-03T11:48:14Z" level=info msg="received unary call /application.ApplicationService/UpdateSpec" grpc.method=UpdateSpec grpc.request.claims="{\"iat\":1597138354,\"iss\":\"argocd\",\"jti\":\"image-updater\",\"nbf\":1597138354,\"sub\":\"image-updater\"}" grpc.request.content="name:\"$APPLICATIONt\" spec:<source:<repoURL:\"$HELM_SOURCE_ENDS_IN_.git\" path:\"$HELM_CHART\" targetRevision:\"HEAD\" helm:<releaseName:\"\" values:\"\" > chart:\"\" > destination:<server:\"https://kubernetes.default.svc\" namespace:\"$APPLICATION\" > project:\"$ARGO_PROJECT\" syncPolicy:<automated:<prune:false selfHeal:false > > > " grpc.service=application.ApplicationService grpc.start_time="2020-09-03T11:48:14Z" span.kind=server system=grpc
time="2020-09-03T11:48:15Z" level=info msg="image-updater updated application spec" application= $APPLICATIONdest-namespace=$APPLICATION dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-09-03T11:48:15Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=UpdateSpec grpc.service=application.ApplicationService grpc.start_time="2020-09-03T11:48:14Z" grpc.time_ms=1171.407 span.kind=server system=grpc
```

Any ideas?

**Comment by jannfis** [comment]
Hi, this seems to be a bug indeed. I guess the defaults for the target parameters are not correctly set. 

As a workaround, can you please try to set the target parameters explicitly, as described here: https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#specifying-helm-parameter-names and see whether the update is done correctly?

**Comment by Zefool** [comment]
Hey, thanks for taking this on :)

So I tried this, but it did not work. The logs have not changed for the image-updater.

I am not sure I did it correctly though. 

Here the Annotations:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/cas.helm.image-name: trusted-ca-service.image.repository
    argocd-image-updater.argoproj.io/cas.helm.image-tag: trusted-ca-service.image.tag
    argocd-image-updater.argoproj.io/image-list: cas=docker.apps.ndgit.com/ndgit/trusted-ca-service:>=2.1.0-0
```

And here the relevant part of the Helm Chart values-file:
```
trusted-ca-service:
  image:
    repository: $REGISTRY/$REPOSITORY/$IMAGE
    tag: 2.1.0-dev.6
```

**Comment by jannfis** [comment]
Your annotations look good as far as I can see.

I suppose that the value for `$IMAGE` in your `argocd-image-updater.argoproj.io/cas.helm.image-name`and `argocd-image-updater.argoproj.io/cas.helm.image-tag` annotations is `trusted-ca-service`?

Are you able to check the `Application` resource, especially the `.spec.source.helm` section? If you have the `jq` tool installed, what does the following give:

```
kubectl -n argocd get applications.argoproj.io <YOURAPP> -o json | jq '.spec.source.helm'
```

Are there any parameter overrides?

**Comment by Zefool** [comment]
> I suppose that the value for $IMAGE in your argocd-image-updater.argoproj.io/cas.helm.image-nameand argocd-image-updater.argoproj.io/cas.helm.image-tag annotations is trusted-ca-service?

Correct

>Are you able to check the Application resource, especially the .spec.source.helm section? 

```
> kubectl -n argocd get applications.argoproj.io trusted-ca-service-test -o json | jq '.spec.source.helm' 
null
```

**Comment by jannfis** [comment]
This is odd, especially considering that according to the logs from one of your above comments, that there should be at least _something_ in the corresponding part of the spec (i.e. it sent `helm:<releaseName:\"\" values:\"\" > chart:\"\"` along with the spec update request).

May I ask what version of Argo CD is running at your side? And I also suppose you are running `v0.5.0` of the image updater?

**Comment by Zefool** [comment]
Sure, here is the Argo setup>

```
argocd-application-controller   1/1     1            1           101d   argocd-application-controller   argoproj/argocd:v1.6.1       app.kubernetes.io/name=argocd-application-controller
argocd-dex-server               1/1     1            1           101d   dex                             quay.io/dexidp/dex:v2.22.0   app.kubernetes.io/name=argocd-dex-server
argocd-redis                    1/1     1            1           101d   redis                           redis:5.0.3                  app.kubernetes.io/name=argocd-redis
argocd-repo-server              1/1     1            1           101d   argocd-repo-server              argoproj/argocd:v1.6.1       app.kubernetes.io/name=argocd-repo-server
argocd-server                   1/1     1            1           101d   argocd-server                   argoproj/argocd:v1.6.1       app.kubernetes.io/name=argocd-server
```

the argocd image is unfortunately set to "latest", and I couldn't find it in Docker Hub anymore. So I deployed a dedicated v0.5.0 , but the logs still say the exact same thing

**Comment by jannfis** [comment]
I'm having a hard time trying to reproduce this. I tried with the `helm-guestbook` chart from `argocd-example-apps` in a live environment and it works as expected.

I will install an Argo CD v1.6.1 and see if it might be an incompatibility between the Argo CD Client (which is v1.6.2 for updater v0.5.0) and the Argo CD server.

In the meanwhile, would you mind sharing non-redacted log files with me, i.e. in a private Gist or something like this? 

Also, do you have any output from `kubectl -n argocd get applications.argoproj.io trusted-ca-service-test -o json | jq '.spec.source.helm'` when you disable the image updater, right after the application has been created and synced? There should be something if you use a `values.yaml`, at least something along the lines of

```
$ kubectl -n argocd get applications.argoproj.io guestbook-helm -o json | jq '.spec.source.helm'
{
  "valueFiles": [
    "values.yaml"
  ]
}
```
If this is `null` also, what is the output of `kubectl -n argocd get applications.argoproj.io <yourapp> -o json | jq '.spec.source'`?

**Comment by jannfis** [comment]
PS: For the records: I wouldn't recommend using `latest` tag for argocd-image-updater image, since this will be an automated build from the current master, and although the builds should work fine, might lead to unexpected (and undocumented) changes.

**Comment by Zefool** [comment]
> kubectl -n argocd get applications.argoproj.io trusted-ca-service-test -o json | jq '.spec.source.helm'
```
{
  "parameters": [
    {
      "forceString": true,
      "name": "image.name",
      "value": "$REGISTRY/$REPOSITORY/$IMAGE"
    },
    {
      "forceString": true,
      "name": "image.tag",
      "value": "2.1.0-dev.102"
    }
  ]
}
```

So that seems to have changed now! I did not disable the image updater before getting this - probably the update?

**Comment by Zefool** [comment]
> I'm having a hard time trying to reproduce this. I tried with the helm-guestbook chart from argocd-example-apps in a live environment and it works as expected.

I'm expecting that maybe the problem lies with our Chart:
```
trusted-ca-service:
  image:
    repository: $REGISTRY/$REPOSITORY/$IMAGE
```
.image.repository is not the same as the expected .image.name - it also includes registry and repository. What do you think?

**Comment by Zefool** [comment]
How do you propose I send you unredacted logs? I'd be open to that, there are no secrets printed

**Comment by jannfis** [comment]
OK, now we're one step further at least with parameters being set. Unfortunately, they seem to be the default parameters (`image.name` and `image.tag`) instead of the ones the chart needs (`trusted-ca-service.image.repository` and `trusted-ca-service.image.tag`).

But I think I found where the problem is. Can you please try if replacing the annotation

```
argocd-image-updater.argoproj.io/image-list: cas=$REGISTRY/$REPOSITORY/$IMAGE:>=2.1.0-0
```
with
```
argocd-image-updater.argoproj.io/image-list: cas=$REGISTRY/$REPOSITORY/$IMAGE:~2.1.0-0
```
will work for you? I think there is a bug in the parser when the version constraint contains an equal sign.

**Comment by jannfis** [comment]
I have just put a fix that's supposed to work for this issue into v0.5.1. Please let me know if that works out for you!

**Comment by Zefool** [comment]
And it immediately runs the new image. Bug fixed, thank you very much!

**Comment by Zefool** [comment]
Just to add, I only updated the image updater to 0.5.1, and did not change the annotation

**Comment by jannfis** [comment]
> And it immediately runs the new image. Bug fixed, thank you very much!

Thanks for your patience and working this out with me! Much appreciated. Glad that it works now.
