### ISSUE TITLE
Regression from #848, missing namespace on CRB

### ISSUE THREAD

**Issue by ef-trss** [argoproj-labs/argocd-image-updater#859]
**Describe the bug**
On the master branch, the [rbac/clusterrolebinding manifest](https://github.com/argoproj-labs/argocd-image-updater/blob/master/manifests/base/rbac/argocd-image-updater-clusterrolebinding.yaml#L14-L15) is missing the namespace for the serviceaccount subject.  This comment sums up the reasoning nicely: https://stackoverflow.com/a/58916117

This change was introduced in #848

**To Reproduce**
1. Create a kustomized app loading argocd-image-updater with the master branch
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj-labs/argocd-image-updater//manifests/base?ref=master
```
2. Install it to your cluster (i.e. `kubectl apply -k .`)
3. Watch for error:
```
Failed sync attempt to 80f2bb4416604c7078416eb843f852f5fe253146: one or more objects failed to apply, reason: error running rbacReconcile: error running kubectl auth reconcile: ClusterRoleBinding.rbac.authorization.k8s.io "argocd-image-updater" is invalid: subjects[0].namespace: Required value
```
**Expected behavior**
No error appears

**Additional context**

**Version**
image-updater: master branch
kubernetes: v1.30.1
ArgoCD: v2.10.15

**Logs**
See above

**Comment by chengfang** [comment]
installing image updater with plain manifests also causes the same failure: 
```bash
k apply -n argocd -f manifests/install.yaml

The ClusterRoleBinding "argocd-image-updater" is invalid: subjects[0].namespace: Required value
```

**Comment by chengfang** [comment]
we'll need to update the 2 files to include namespace for the service account:
* manifests/base/rbac/argocd-image-updater-clusterrolebinding.yaml
* manifests/install.yaml

I think we can use `argocd` as the SA namespace and update the docs to reminder users to change it if they are installing the image updater in different namespace.

This is how argocd handles it:
https://argo-cd.readthedocs.io/en/stable/getting_started/
>The installation manifests include ClusterRoleBinding resources that reference argocd namespace. If you are installing Argo CD into a different namespace then make sure to update the namespace reference.
