### ISSUE TITLE
The release v0.15.0 misses the checksum file `release-v0.15.0.sha256`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [argoproj-labs/argocd-image-updater#898]
https://github.com/argoproj-labs/argocd-image-updater/releases/tag/v0.15.0

The release v0.15.0 misses checksum files `release-v0.15.0.sha256` and `release-v0.15.0.sha256.asc`.

**Comment by chengfang** [comment]
In v0.14.0 or earlier releases, the checksum and signature file were created and uploaded by
https://github.com/argoproj-labs/argocd-image-updater/blob/master/hack/upload-multiarch-release-assets.sh#L21

We need to update the github action https://github.com/argoproj-labs/argocd-image-updater/blob/master/.github/workflows/create-release-draft.yaml to do the similar steps.

**Comment by chengfang** [comment]
I uploaded the 2 missing files to [v0.15.0](https://github.com/argoproj-labs/argocd-image-updater/releases/tag/v0.15.0)
