### ISSUE TITLE
Image updater helm chart 0.11.2 changes git write back file

### ISSUE THREAD

**Issue by jdautomate** [argoproj-labs/argocd-image-updater#963]
**Describe the bug**
We have been using the image-updater for a long time, with this update the git write back file changed from:
`.argocd-source-www.yaml`
to:
`argocd-source-argocd_www.yaml`

Result is I have 2 files in source control and argocd is looking at the wrong one.  ArgoCD version 2.13.1 does not recognize the new `argocd-source-argocd_www.yaml` file.  Therefore the image is not updated.

I assume this is to support multiple namespaces, so argocd applications can live anywhere in the cluster.  Am I missing a config here on the argocd or argocd-image-updater side?

**To Reproduce**
Upgrade to latest helm chart version, have image updater using git write back method.
ArgoCD version 2.13.1 running in EKS cluster
Target application running in argocd namespace 

**Expected behavior**
Expect argocd to be able to use the new write back file.

**Additional context**

**Version**
Helm 0.11.2
App v0.15.1

**Logs**
Logs are showing no image to update.

**Comment by chengfang** [comment]
This change was introduced in https://github.com/argoproj-labs/argocd-image-updater/pull/763 , to support non-control-plane namespaces. In update.go https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/argocd/update.go#L655 there is condition to decide whether to include namespace in the file name. If the application namespace is not set or is the same as control plane namespace, the generated file should be the same as before. Can you check what has led your app to use the file name with namespace?

**Comment by jdautomate** [comment]
Thanks for the quick response.  My image updater config has not changed recently:
`project: saas-apps
source:
  repoURL: 'https://argoproj.github.io/argo-helm'
  targetRevision: 0.11.0
  helm:
    valuesObject:
      authScripts:
        enabled: true
        scripts:
          ecr-login.sh: >
            #!/bin/sh

            aws ecr get-login-password --region "us-west-1" | awk '{print
            "AWS:"$1}'
          ecr.sh: >
            #!/bin/sh

            aws ecr --region "us-west-1" get-authorization-token --output text
            --query 'authorizationData[].authorizationToken' | base64 -d
      config:
        applicationsAPIKind: argocd
        argocd:
          grpcWeb: true
          insecure: true
          plaintext: false
          serverAddress: argocd-server.argocd
          token: ''
        disableKubeEvents: false
        gitCommitMail: argocd-image-updater@xxxx
        gitCommitTemplate: argocd image updater commit
        gitCommitUser: argocd-image-updater
        logLevel: debug
        registries:
          - api_url: 'https://quay.io'
            name: RedHat Quay
            ping: false
          - api_url: 'xxxx'
            credentials: 'ext:/scripts/ecr.sh'
            credsexpire: 11h
            insecure: false
            name: ECR
            ping: true
            prefix: xxxx
          - api_url: 'xxxx'
            credentials: 'ext:/scripts/ecr-login.sh'
            credsexpire: 11h
            insecure: false
            name: shared-prod
            ping: true
            prefix: xxxx
        sshConfig:
          config: |
            Host *
                  PubkeyAcceptedAlgorithms +ssh-rsa
                  HostkeyAlgorithms +ssh-rsa
      extraArgs:
        - '--interval'
        - 2m
      extraEnv:
        - name: AWS_REGION
          value: us-west-1
`
I see the conditional, how can I make my config use this DefaultTargetFilePatternWithoutNamespace option?

**Comment by chengfang** [comment]
I'm seeing the same in my sample app https://github.com/chengfang/image-updater-examples/tree/main/push-branch-kustomize, which writes to the file name [argocd-source-argocd_push-branch-kustomize.yaml](push-branch-kustomize/source/.argocd-source-argocd_push-branch-kustomize.yaml). I'll look into it.

**Comment by jdautomate** [comment]
Thanks!!

**Comment by chengfang** [comment]
looks like there is a bug how the argocd control plane namespace is retrieved in https://github.com/argoproj-labs/argocd-image-updater/blob/8076d2005ea625c73604073fca43df38eb675751/pkg/argocd/update.go#L655

In the above line, `KubeClient.Namespace` returns a value like `default`, which is different from what we would expect, and different from the appNamespace `argocd`. We'd expected it to return `argocd` so it would match the appNamespace in order to omit namespade in the target file name. Will need to figure out the correct way to get the argocd namespace.

**Comment by chengfang** [comment]
If we pass the args `--argocd-namespace argocd` to image-updater executable, that tells image-updater to use that as the argocd control plane namespace, instead of inferring it from the client config.

When running image-updater with that args from command line, no namespace is used in the git repo write-back target file.
```bash
dist/argocd-image-updater run --once --argocd-namespace argocd
```
In contrast, running image-updater without `--argocd-namespace argocd` args results in a git repo write-back target file named with namespace such as `.argocd-source-argocd_push-branch-kustomize.yaml`

When running image-updater as a kubernetes workload, you can pass the same args to the container, or as environment variable.
```yaml
    spec:
      containers:
      - args:
        - run
        - --argocd-namespace=argocd
```
That said, it is still a bug we'll try to fix.

**Comment by chengfang** [comment]
Just to clarify the reproducibility of this issue, when running image-updater from command line without `--argocd-namespace argocd`, this issue exists (target file name contains appNamespace).  To avoid this issue when running from command line, specify args `--argocd-namespace argocd`.

When running image-updater as Kubernetes workload, I couldn't reproduce it, i.e., the correct target file name is generated: when appNamespace is the same as argocd control plane namespace, the target file does not include namespace.

For example, https://github.com/chengfang/image-updater-examples/commit/bc383dc6d113805c30e50ec78ee735348560deb3 is the target file created when running image-updater in the argocd control plane namespace. image-updater was installed using https://github.com/argoproj-labs/argocd-image-updater/blob/master/manifests/install.yaml without any extra configuration.

```shell
kubectl logs -n argocd pods/argocd-image-updater-765b7f4c47-g8n2n -f

time="2024-12-11T19:04:35Z" level=info msg="argocd-image-updater v99.9.9+fe1ac46 starting [loglevel:INFO, interval:2m0s, healthport:8080]"
time="2024-12-11T19:04:35Z" level=warning msg="commit message template at /app/config/commit.template does not exist, using default"
time="2024-12-11T19:04:35Z" level=warning msg="Registry configuration at /app/config/registries.conf could not be read: stat /app/config/registries.conf: no such file or directory -- using default configuration"
time="2024-12-11T19:04:35Z" level=info msg="ArgoCD configuration: [apiKind=kubernetes, server=argocd-server.argocd, auth_token=false, insecure=false, grpc_web=false, plaintext=false]"

time="2024-12-11T19:04:35Z" level=info msg="Starting health probe server TCP port=8080"
time="2024-12-11T19:04:35Z" level=info msg="Starting metrics server on TCP port=8081"
time="2024-12-11T19:04:35Z" level=info msg="Warming up image cache"
time="2024-12-11T19:04:37Z" level=info msg="Setting new image to nginx:1.16.1" alias=nginx application=push-branch-kustomize image_name=nginx image_tag=1.16.0 registry=
time="2024-12-11T19:04:37Z" level=info msg="Successfully updated image 'nginx:1.16.0' to 'nginx:1.16.1', but pending spec update (dry run=true)" alias=nginx application=push-branch-kustomize image_name=nginx image_tag=1.16.0 registry=
time="2024-12-11T19:04:37Z" level=info msg="Dry run - not committing 1 changes to application" application=push-branch-kustomize
time="2024-12-11T19:04:37Z" level=info msg="Finished cache warm-up, pre-loaded 0 meta data entries from 1 registries"
time="2024-12-11T19:04:37Z" level=info msg="Starting image update cycle, considering 1 annotated application(s) for update"
time="2024-12-11T19:04:37Z" level=info msg="Setting new image to nginx:1.16.1" alias=nginx application=push-branch-kustomize image_name=nginx image_tag=1.16.0 registry=
time="2024-12-11T19:04:37Z" level=info msg="Successfully updated image 'nginx:1.16.0' to 'nginx:1.16.1', but pending spec update (dry run=false)" alias=nginx application=push-branch-kustomize image_name=nginx image_tag=1.16.0 registry=
time="2024-12-11T19:04:37Z" level=info msg="Committing 1 parameter update(s) for application push-branch-kustomize" application=push-branch-kustomize
time="2024-12-11T19:04:37Z" level=info msg="Initializing https://github.com/chengfang/image-updater-examples.git to /tmp/git-push-branch-kustomize2539368525"
time="2024-12-11T19:04:37Z" level=info msg="writing to hasher nginx-1.16.0-1.16.1,"
time="2024-12-11T19:04:37Z" level=info msg="git fetch origin push-branch --force --prune --depth 1" dir=/tmp/git-push-branch-kustomize2539368525 execID=6f391
time="2024-12-11T19:04:38Z" level=info msg=Trace args="[git fetch origin push-branch --force --prune --depth 1]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=475.85737500000005
time="2024-12-11T19:04:38Z" level=info msg="git checkout --force push-branch" dir=/tmp/git-push-branch-kustomize2539368525 execID=46843
time="2024-12-11T19:04:38Z" level=info msg=Trace args="[git checkout --force push-branch]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=2.590166
time="2024-12-11T19:04:38Z" level=info msg="git clean -ffdx" dir=/tmp/git-push-branch-kustomize2539368525 execID=6ab23
time="2024-12-11T19:04:38Z" level=info msg=Trace args="[git clean -ffdx]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=0.61925
time="2024-12-11T19:04:38Z" level=info msg="git add /tmp/git-push-branch-kustomize2539368525/push-branch-kustomize/source/.argocd-source-push-branch-kustomize.yaml" dir=/tmp/git-push-branch-kustomize2539368525 execID=f9b76
time="2024-12-11T19:04:38Z" level=info msg=Trace args="[git add /tmp/git-push-branch-kustomize2539368525/push-branch-kustomize/source/.argocd-source-push-branch-kustomize.yaml]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=0.7679590000000001
time="2024-12-11T19:04:38Z" level=info msg="git config user.name argocd-image-updater" dir=/tmp/git-push-branch-kustomize2539368525 execID=b7129
time="2024-12-11T19:04:38Z" level=info msg=Trace args="[git config user.name argocd-image-updater]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=0.46725
time="2024-12-11T19:04:38Z" level=info msg="git config user.email noreply@argoproj.io" dir=/tmp/git-push-branch-kustomize2539368525 execID=e91a0
time="2024-12-11T19:04:38Z" level=info msg=Trace args="[git config user.email noreply@argoproj.io]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=0.45637500000000003
time="2024-12-11T19:04:38Z" level=info msg="git -c gpg.format=openpgp commit -a -F /tmp/image-updater-commit-msg471748922" dir=/tmp/git-push-branch-kustomize2539368525 execID=49394
time="2024-12-11T19:04:38Z" level=info msg=Trace args="[git -c gpg.format=openpgp commit -a -F /tmp/image-updater-commit-msg471748922]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=2.109834
time="2024-12-11T19:04:38Z" level=info msg="git push -f origin push-branch" dir=/tmp/git-push-branch-kustomize2539368525 execID=5f178
time="2024-12-11T19:04:39Z" level=info msg=Trace args="[git push -f origin push-branch]" dir=/tmp/git-push-branch-kustomize2539368525 operation_name="exec git" time_ms=924.727709
time="2024-12-11T19:04:39Z" level=info msg="Successfully updated the live application spec" application=push-branch-kustomize
time="2024-12-11T19:04:39Z" level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=1 errors=0"
```

**Comment by jdautomate** [comment]
This is good info, thank you
