### ISSUE TITLE
No valid auth entry for registry https://ghcr.io found

### ISSUE THREAD

**Issue by windsource** [argoproj-labs/argocd-image-updater#97]
**Describe the bug**

ArgoCD image updater cannot find the login for a registry if https:// prefix is missing in secret. If prefix is added to secret it works fine.

**To Reproduce**

I login to a registry using

```bash
docker login ghcr.io
```

and use the resulting ~/.docker/config.json file to create a secret of type kubernetes.io/dockerconfigjson.

Then I start ArgoCD image updater and get the log:

```
time="2020-09-25T19:56:16Z" level=error msg="Could not set registry endpoint credentials: no valid auth entry for registry https://ghcr.io found in image pull secret ...  registry=ghcr.io"
```

If the secret is created with `docker login https://ghcr.io` it works fine.

**Expected behavior**

ArgoCD image updater should find the login even if https:// prefix is missing in secret.

**Additional context**

**Version**
v0.6.2

**Comment by jannfis** [comment]
Thanks for writing this down, @windsource! 

I guess every second person using the image updater already tripped over this, and I kept forgetting to create an issue. :)
